# Localization source: common UI, onboarding, discovery, pairing, remote, keyboard, apps.
# Tuple order: (en, es, ru, de, fr).

STRINGS = {
    # Common
    "common.cancel": ("Cancel", "Cancelar", "Отмена", "Abbrechen", "Annuler"),
    "common.close": ("Close", "Cerrar", "Закрыть", "Schließen", "Fermer"),
    "common.dismiss": ("Dismiss", "Descartar", "Скрыть", "Ausblenden", "Masquer"),
    "common.done": ("Done", "Listo", "Готово", "Fertig", "OK"),
    "common.save": ("Save", "Guardar", "Сохранить", "Sichern", "Enregistrer"),
    "common.getHelp": ("Get help", "Obtener ayuda", "Помощь", "Hilfe", "Obtenir de l’aide"),
    "common.errorCode": ("Code: %@", "Código: %@", "Код: %@", "Code: %@", "Code : %@"),
    "common.errorCode.accessibility": ("Error code %@", "Código de error %@", "Код ошибки %@", "Fehlercode %@", "Code d’erreur %@"),

    # Tabs
    "tab.remote": ("Remote", "Mando", "Пульт", "Fernbedienung", "Télécommande"),
    "tab.cast": ("Cast", "Enviar", "Показ", "Übertragen", "Diffuser"),
    "tab.settings": ("Settings", "Ajustes", "Настройки", "Einstellungen", "Réglages"),

    # Welcome / onboarding
    "welcome.pricingNote": ("Free to download and to check your TV. Continued use needs Remote Pro (monthly, yearly or one‑time purchase) — no ads, no account.",
                            "Descarga y comprobación de tu TV gratis. Para seguir usándolo necesitas Remote Pro (mensual, anual o pago único), sin anuncios ni cuenta.",
                            "Скачивание и проверка телевизора бесплатны. Для дальнейшего использования нужен Remote Pro (месяц, год или разовая покупка) — без рекламы и регистрации.",
                            "Download und TV-Check sind kostenlos. Für die weitere Nutzung brauchst du Remote Pro (monatlich, jährlich oder einmalig) – ohne Werbung, ohne Konto.",
                            "Téléchargement et vérification du téléviseur gratuits. L’utilisation continue nécessite Remote Pro (mensuel, annuel ou achat unique), sans pub ni compte."),
    "explain.title": ("Before we look for your TV", "Antes de buscar tu TV", "Перед поиском телевизора", "Bevor wir deinen Fernseher suchen", "Avant de rechercher votre téléviseur"),
    "explain.sameNetwork": ("Your iPhone and TV must be on the same Wi‑Fi network. Any band works as long as the devices can reach each other.",
                            "El iPhone y la TV deben estar en la misma red Wi‑Fi. Sirve cualquier banda si los dispositivos se ven entre sí.",
                            "iPhone и телевизор должны быть в одной сети Wi‑Fi. Частота не важна, если устройства видят друг друга.",
                            "iPhone und Fernseher müssen im selben WLAN sein. Jedes Frequenzband geht, solange sich die Geräte erreichen.",
                            "L’iPhone et le téléviseur doivent être sur le même réseau Wi‑Fi. N’importe quelle bande convient si les appareils se voient."),
    "explain.tvOn": ("Turn the TV on. A TV that is fully off usually can’t be found over the network.",
                     "Enciende la TV. Una TV totalmente apagada normalmente no se puede encontrar por la red.",
                     "Включите телевизор. Полностью выключенный телевизор обычно не виден в сети.",
                     "Schalte den Fernseher ein. Ein ganz ausgeschalteter Fernseher ist im Netzwerk meist nicht auffindbar.",
                     "Allumez le téléviseur. Un téléviseur complètement éteint est généralement introuvable sur le réseau."),
    "explain.permission": ("iOS will ask for Local Network access. It’s needed to find the TV and send commands to it.",
                           "iOS pedirá acceso a la red local. Es necesario para encontrar la TV y enviarle órdenes.",
                           "iOS запросит доступ к локальной сети. Он нужен, чтобы найти телевизор и отправлять ему команды.",
                           "iOS fragt nach Zugriff auf das lokale Netzwerk. Er wird gebraucht, um den Fernseher zu finden und zu steuern.",
                           "iOS demandera l’accès au réseau local. Il sert à trouver le téléviseur et à lui envoyer des commandes."),
    "explain.privacy": ("Commands, photos and your screen go directly to your TV on your home network — not to our servers.",
                        "Las órdenes, fotos y tu pantalla van directamente a la TV por tu red doméstica, no a nuestros servidores.",
                        "Команды, фото и изображение экрана идут напрямую на телевизор через домашнюю сеть, а не на наши серверы.",
                        "Befehle, Fotos und dein Bildschirm gehen direkt über dein Heimnetz an den Fernseher – nicht an unsere Server.",
                        "Les commandes, photos et votre écran vont directement au téléviseur via votre réseau domestique, pas vers nos serveurs."),
    "explain.continue": ("Find my TV", "Buscar mi TV", "Найти телевизор", "Fernseher suchen", "Trouver mon téléviseur"),

    # Discovery
    "discovery.title": ("Connect TV", "Conectar TV", "Подключить ТВ", "Fernseher verbinden", "Connecter le téléviseur"),
    "discovery.saved": ("Saved TVs", "TV guardadas", "Сохранённые ТВ", "Gespeicherte Fernseher", "Téléviseurs enregistrés"),
    "discovery.found": ("On this network", "En esta red", "В этой сети", "In diesem Netzwerk", "Sur ce réseau"),
    "discovery.searching": ("Looking for TVs…", "Buscando TV…", "Ищем телевизоры…", "Suche nach Fernsehern …", "Recherche de téléviseurs…"),
    "discovery.searching.detail": ("This can take up to 20 seconds.", "Puede tardar hasta 20 segundos.", "Это может занять до 20 секунд.", "Das kann bis zu 20 Sekunden dauern.", "Cela peut prendre jusqu’à 20 secondes."),
    "discovery.progress": ("Search progress", "Progreso de la búsqueda", "Ход поиска", "Suchfortschritt", "Progression de la recherche"),
    "discovery.empty.title": ("No TVs found yet", "Aún no se encontró ninguna TV", "Телевизоры пока не найдены", "Noch keine Fernseher gefunden", "Aucun téléviseur trouvé pour l’instant"),
    "discovery.empty.message": ("Check that the TV is on, on the same Wi‑Fi, and not on a guest network. A VPN on the iPhone can also block the search.",
                                "Comprueba que la TV esté encendida, en el mismo Wi‑Fi y no en una red de invitados. Una VPN en el iPhone también puede bloquear la búsqueda.",
                                "Проверьте, что телевизор включён, находится в той же сети Wi‑Fi и не в гостевой. VPN на iPhone тоже может мешать поиску.",
                                "Prüfe, ob der Fernseher an, im selben WLAN und nicht im Gastnetz ist. Auch ein VPN auf dem iPhone kann die Suche blockieren.",
                                "Vérifiez que le téléviseur est allumé, sur le même Wi‑Fi et pas sur un réseau invité. Un VPN sur l’iPhone peut aussi bloquer la recherche."),
    "discovery.searchAgain": ("Search again", "Buscar de nuevo", "Искать снова", "Erneut suchen", "Relancer la recherche"),
    "discovery.skip": ("Continue without a TV for now", "Continuar sin TV por ahora", "Продолжить пока без телевизора", "Vorerst ohne Fernseher fortfahren", "Continuer sans téléviseur pour l’instant"),
    "discovery.troubleshoot": ("TV not found? Get help", "¿No aparece la TV? Obtener ayuda", "Телевизор не найден? Помощь", "Fernseher nicht gefunden? Hilfe", "Téléviseur introuvable ? Aide"),
    "discovery.multicastNote": ("Some TVs are found by scanning your network, which can take a little longer.",
                                "Algunas TV se encuentran explorando la red, lo que puede tardar un poco más.",
                                "Некоторые телевизоры находятся сканированием сети — это может занять чуть больше времени.",
                                "Manche Fernseher werden durch Scannen des Netzwerks gefunden, das kann etwas dauern.",
                                "Certains téléviseurs sont trouvés en analysant le réseau, ce qui peut prendre un peu plus de temps."),
    "device.status.connected": ("Connected", "Conectada", "Подключён", "Verbunden", "Connecté"),
    "device.status.disconnected": ("Not connected", "Sin conexión", "Не подключён", "Nicht verbunden", "Non connecté"),
    "device.status.notSeen": ("Not found now", "No encontrada ahora", "Сейчас не найден", "Gerade nicht gefunden", "Introuvable pour l’instant"),
    "device.connect.hint": ("Connects to this TV", "Conecta con esta TV", "Подключиться к этому телевизору", "Mit diesem Fernseher verbinden", "Se connecter à ce téléviseur"),

    # Pairing
    "pairing.yourTV": ("your TV", "tu TV", "ваш телевизор", "deinem Fernseher", "votre téléviseur"),
    "pairing.confirm.title": ("Confirm on your TV", "Confirma en la TV", "Подтвердите на телевизоре", "Am Fernseher bestätigen", "Confirmez sur le téléviseur"),
    "pairing.confirm.message": ("Accept the connection request on “%@” with the TV remote.", "Acepta la solicitud de conexión en «%@» con el mando de la TV.", "Примите запрос на подключение на «%@» с помощью пульта телевизора.", "Nimm die Verbindungsanfrage auf „%@“ mit der TV-Fernbedienung an.", "Acceptez la demande de connexion sur « %@ » avec la télécommande du téléviseur."),
    "pairing.waiting": ("Waiting for the TV", "Esperando a la TV", "Ожидание телевизора", "Warten auf den Fernseher", "En attente du téléviseur"),
    "pairing.pin.title": ("Enter the code from the TV", "Introduce el código de la TV", "Введите код с экрана ТВ", "Code vom Fernseher eingeben", "Saisissez le code du téléviseur"),
    "pairing.pin.message": ("A 6‑character code is shown on the TV screen.", "La TV muestra un código de 6 caracteres.", "На экране телевизора показан код из 6 символов.", "Auf dem Fernseher wird ein 6‑stelliger Code angezeigt.", "Un code de 6 caractères s’affiche sur le téléviseur."),
    "pairing.pin.retry": ("That code didn’t match. Check the letters and numbers on the TV and type it again.", "Ese código no coincide. Revisa las letras y números de la TV y escríbelo otra vez.", "Код не подошёл. Проверьте буквы и цифры на экране и введите снова.", "Der Code stimmt nicht. Prüfe Buchstaben und Zahlen am Fernseher und gib ihn erneut ein.", "Ce code ne correspond pas. Vérifiez les lettres et chiffres et saisissez-le à nouveau."),
    "pairing.pin.placeholder": ("Code", "Código", "Код", "Code", "Code"),
    "pairing.pin.accessibility": ("Pairing code from the TV", "Código de vinculación de la TV", "Код сопряжения с телевизора", "Kopplungscode vom Fernseher", "Code d’association du téléviseur"),
    "pairing.pin.submit": ("Connect", "Conectar", "Подключить", "Verbinden", "Connecter"),

    # Compatibility
    "compat.title": ("Compatibility check", "Comprobación de compatibilidad", "Проверка совместимости", "Kompatibilitätsprüfung", "Vérification de compatibilité"),
    "compat.results": ("Results for this TV", "Resultados para esta TV", "Результаты для этого ТВ", "Ergebnisse für diesen Fernseher", "Résultats pour ce téléviseur"),
    "compat.footer": ("Each feature is checked separately on your TV. A working remote doesn’t mean every other feature works.",
                      "Cada función se comprueba por separado en tu TV. Que el mando funcione no implica que funcione todo lo demás.",
                      "Каждая функция проверяется отдельно. Работающий пульт не означает, что работают все остальные функции.",
                      "Jede Funktion wird einzeln an deinem Fernseher geprüft. Eine funktionierende Fernbedienung heißt nicht, dass alles andere funktioniert.",
                      "Chaque fonction est vérifiée séparément. Une télécommande qui fonctionne ne signifie pas que tout le reste fonctionne."),
    "compat.continue": ("Continue", "Continuar", "Продолжить", "Weiter", "Continuer"),
    "compat.notConnected.title": ("No TV connected", "No hay TV conectada", "Телевизор не подключён", "Kein Fernseher verbunden", "Aucun téléviseur connecté"),
    "compat.notConnected.message": ("Connect a TV to check what works with it.", "Conecta una TV para ver qué funciona con ella.", "Подключите телевизор, чтобы проверить, что с ним работает.", "Verbinde einen Fernseher, um zu prüfen, was funktioniert.", "Connectez un téléviseur pour vérifier ce qui fonctionne."),

    # Header
    "header.noTV": ("No TV", "Sin TV", "Нет ТВ", "Kein Fernseher", "Aucun téléviseur"),
    "header.addTV": ("Add TV", "Añadir TV", "Добавить ТВ", "Fernseher hinzufügen", "Ajouter un téléviseur"),
    "header.accessibility": ("Current TV: %@. Choose another TV", "TV actual: %@. Elegir otra TV", "Текущий ТВ: %@. Выбрать другой", "Aktueller Fernseher: %@. Anderen wählen", "Téléviseur actuel : %@. En choisir un autre"),
    "header.switch.mirroring.title": ("Stop the current session?", "¿Detener la sesión actual?", "Остановить текущий показ?", "Aktuelle Sitzung beenden?", "Arrêter la session en cours ?"),
    "header.switch.mirroring.message": ("Showing on the current TV will stop before switching.", "El contenido en la TV actual se detendrá antes de cambiar.", "Показ на текущем телевизоре будет остановлен перед переключением.", "Die Wiedergabe auf dem aktuellen Fernseher wird vor dem Wechsel beendet.", "L’affichage sur le téléviseur actuel s’arrêtera avant le changement."),
    "header.switch.mirroring.confirm": ("Stop and switch", "Detener y cambiar", "Остановить и переключить", "Beenden und wechseln", "Arrêter et changer"),

    # Remote
    "remote.noTV.title": ("No TV yet", "Aún no hay TV", "Телевизор не выбран", "Noch kein Fernseher", "Pas encore de téléviseur"),
    "remote.noTV.message": ("Find your TV on the Wi‑Fi network to start.", "Busca tu TV en la red Wi‑Fi para empezar.", "Найдите телевизор в сети Wi‑Fi, чтобы начать.", "Suche deinen Fernseher im WLAN, um zu starten.", "Trouvez votre téléviseur sur le Wi‑Fi pour commencer."),
    "remote.noTV.action": ("Connect TV", "Conectar TV", "Подключить ТВ", "Fernseher verbinden", "Connecter le téléviseur"),
    "remote.status.disconnected": ("“%@” is not connected.", "«%@» no está conectada.", "«%@» не подключён.", "„%@“ ist nicht verbunden.", "« %@ » n’est pas connecté."),
    "remote.status.connecting": ("Connecting…", "Conectando…", "Подключение…", "Verbindung wird hergestellt …", "Connexion…"),
    "remote.status.reconnecting": ("Reconnecting (attempt %lld of 3)…", "Reconectando (intento %lld de 3)…", "Переподключение (попытка %lld из 3)…", "Neue Verbindung (Versuch %lld von 3) …", "Reconnexion (tentative %lld sur 3)…"),
    "remote.reconnect": ("Reconnect", "Reconectar", "Подключить", "Neu verbinden", "Reconnecter"),
    "remote.wake": ("Try turning on over Wi‑Fi", "Intentar encender por Wi‑Fi", "Попробовать включить по Wi‑Fi", "Über WLAN einschalten versuchen", "Essayer d’allumer via Wi‑Fi"),
    "remote.wake.sent": ("Wake signal sent. If the TV stays off, use its own remote — not every TV allows this.", "Señal enviada. Si la TV sigue apagada, usa su propio mando: no todas lo permiten.", "Сигнал отправлен. Если телевизор не включился, используйте его пульт — не все модели это поддерживают.", "Wecksignal gesendet. Bleibt der Fernseher aus, nutze seine Fernbedienung – nicht jedes Gerät erlaubt das.", "Signal envoyé. Si le téléviseur reste éteint, utilisez sa télécommande : tous ne le permettent pas."),
    "remote.wake.notPermitted": ("This version can’t send the wake signal on your network. Turn the TV on with its own remote.", "Esta versión no puede enviar la señal en tu red. Enciende la TV con su mando.", "Эта версия не может отправить сигнал включения в вашей сети. Включите телевизор его пультом.", "Diese Version kann das Wecksignal in deinem Netzwerk nicht senden. Schalte den Fernseher mit seiner Fernbedienung ein.", "Cette version ne peut pas envoyer le signal sur votre réseau. Allumez le téléviseur avec sa télécommande."),
    "remote.wake.unavailable": ("If the TV is off, turn it on with its own remote.", "Si la TV está apagada, enciéndela con su mando.", "Если телевизор выключен, включите его пультом.", "Ist der Fernseher aus, schalte ihn mit seiner Fernbedienung ein.", "Si le téléviseur est éteint, allumez-le avec sa télécommande."),
    "remote.style": ("Navigation", "Navegación", "Навигация", "Navigation", "Navigation"),
    "remote.style.dpad": ("Buttons", "Botones", "Кнопки", "Tasten", "Touches"),
    "remote.style.touchpad": ("Touchpad", "Panel táctil", "Тачпад", "Touchpad", "Pavé tactile"),
    "remote.compatibility": ("What works on this TV", "Qué funciona en esta TV", "Что работает на этом ТВ", "Was mit diesem Fernseher funktioniert", "Ce qui fonctionne sur ce téléviseur"),
    "remote.options": ("Remote options", "Opciones del mando", "Настройки пульта", "Fernbedienungsoptionen", "Options de télécommande"),
    "remote.keyboard": ("Keyboard", "Teclado", "Клавиатура", "Tastatur", "Clavier"),
    "remote.volume": ("VOL", "VOL", "ГРОМК", "LAUT", "VOL"),
    "remote.channel": ("CH", "CAN", "КАН", "PROG", "CH"),
    "remote.more.title": ("More buttons", "Más botones", "Другие кнопки", "Weitere Tasten", "Autres touches"),
    "remote.dpad.accessibility": ("Navigation buttons", "Botones de navegación", "Кнопки навигации", "Navigationstasten", "Touches de navigation"),
    "remote.touchpad.hint": ("Swipe to move, tap to select", "Desliza para moverte y toca para seleccionar", "Проведите для перемещения, коснитесь для выбора", "Wischen zum Bewegen, tippen zum Auswählen", "Balayez pour vous déplacer, touchez pour sélectionner"),
    "remote.touchpad.accessibility": ("Touchpad", "Panel táctil", "Тачпад", "Touchpad", "Pavé tactile"),
    "remote.touchpad.accessibilityHint": ("Swipe up or down to move. Double-tap to select. The Buttons layout offers all directions.", "Desliza arriba o abajo para moverte. Toca dos veces para seleccionar. El diseño Botones ofrece todas las direcciones.", "Смахните вверх или вниз для перемещения. Дважды коснитесь для выбора. В режиме «Кнопки» доступны все направления.", "Nach oben oder unten wischen zum Bewegen. Doppeltippen zum Auswählen. Das Tasten-Layout bietet alle Richtungen.", "Balayez vers le haut ou le bas pour vous déplacer. Touchez deux fois pour sélectionner. La disposition Touches offre toutes les directions."),

    # Access status
    "access.verifying": ("Checking your Remote Pro access…", "Comprobando tu acceso a Remote Pro…", "Проверяем доступ Remote Pro…", "Remote Pro-Zugriff wird geprüft …", "Vérification de votre accès Remote Pro…"),

    # Diagnostic allowance (remote)
    "diagnostic.unlock": ("Continue with Remote Pro", "Continuar con Remote Pro", "Продолжить с Remote Pro", "Mit Remote Pro fortfahren", "Continuer avec Remote Pro"),
    "diagnostic.remote.exhausted": ("The free check on this TV is used up. The remote works here — Remote Pro keeps it going.", "La comprobación gratuita en esta TV se agotó. El mando funciona aquí; Remote Pro permite seguir usándolo.", "Бесплатная проверка на этом телевизоре закончилась. Пульт здесь работает — Remote Pro позволит продолжить.", "Der kostenlose Test auf diesem Fernseher ist aufgebraucht. Die Fernbedienung funktioniert hier – mit Remote Pro geht es weiter.", "La vérification gratuite est épuisée sur ce téléviseur. La télécommande fonctionne ici : Remote Pro permet de continuer."),
    "diagnostic.unlock.short": ("Unlock", "Desbloquear", "Открыть", "Freischalten", "Débloquer"),
    "diagnostic.photo.available": ("You can show one test photo on this TV for free.", "Puedes mostrar gratis una foto de prueba en esta TV.", "Вы можете бесплатно показать одно тестовое фото на этом телевизоре.", "Du kannst ein Testfoto kostenlos auf diesem Fernseher zeigen.", "Vous pouvez afficher gratuitement une photo test sur ce téléviseur."),

    # Keyboard
    "keyboard.title": ("Keyboard", "Teclado", "Клавиатура", "Tastatur", "Clavier"),
    "keyboard.placeholder": ("Type here", "Escribe aquí", "Введите текст", "Hier tippen", "Tapez ici"),
    "keyboard.field.accessibility": ("Text to send to the TV", "Texto para enviar a la TV", "Текст для отправки на ТВ", "Text für den Fernseher", "Texte à envoyer au téléviseur"),
    "keyboard.selectField": ("Select a text field on your TV", "Selecciona un campo de texto en la TV", "Выберите поле ввода на телевизоре", "Wähle ein Textfeld auf dem Fernseher", "Sélectionnez un champ de texte sur le téléviseur"),
    "keyboard.fieldActive": ("A text field is active on the TV.", "Hay un campo de texto activo en la TV.", "На телевизоре активно поле ввода.", "Auf dem Fernseher ist ein Textfeld aktiv.", "Un champ de texte est actif sur le téléviseur."),
    "keyboard.hint.sendCompleted": ("Open a search field on the TV, type here, then tap Send.", "Abre un campo de búsqueda en la TV, escribe aquí y toca Enviar.", "Откройте поле поиска на телевизоре, наберите текст здесь и нажмите «Отправить».", "Öffne ein Suchfeld am Fernseher, tippe hier und tippe dann auf „Senden“.", "Ouvrez un champ de recherche sur le téléviseur, tapez ici puis touchez Envoyer."),
    "keyboard.send": ("Send", "Enviar", "Отправить", "Senden", "Envoyer"),
    "keyboard.search": ("Search / Enter", "Buscar / Intro", "Поиск / Ввод", "Suchen / Enter", "Rechercher / Entrée"),
    "keyboard.clear": ("Clear", "Borrar", "Очистить", "Löschen", "Effacer"),
    "keyboard.resend": ("Send again", "Enviar de nuevo", "Отправить снова", "Erneut senden", "Renvoyer"),
    "keyboard.status.sending": ("Sending…", "Enviando…", "Отправка…", "Wird gesendet …", "Envoi…"),
    "keyboard.status.sent": ("Sent to the TV", "Enviado a la TV", "Отправлено на ТВ", "An den Fernseher gesendet", "Envoyé au téléviseur"),
    "keyboard.status.unknown": ("Not sure the last text arrived. Check the TV.", "No se sabe si llegó el último texto. Revisa la TV.", "Неизвестно, дошёл ли последний текст. Проверьте телевизор.", "Unklar, ob der letzte Text angekommen ist. Prüfe den Fernseher.", "Impossible de confirmer l’envoi du dernier texte. Vérifiez le téléviseur."),
    "keyboard.privacyNote": ("Typed text goes only to your TV. It isn’t saved or sent to analytics. Passwords may not work in every TV app.", "El texto solo va a tu TV. No se guarda ni se envía a analíticas. Puede que las contraseñas no funcionen en todas las apps.", "Текст отправляется только на телевизор. Он не сохраняется и не попадает в аналитику. Пароли могут работать не во всех приложениях ТВ.", "Getippter Text geht nur an deinen Fernseher. Er wird weder gespeichert noch analysiert. Passwörter funktionieren nicht in jeder TV-App.", "Le texte va uniquement à votre téléviseur. Il n’est ni enregistré ni envoyé aux statistiques. Les mots de passe peuvent ne pas fonctionner dans toutes les apps."),
    "keyboard.unsupported.title": ("Typing isn’t available", "No se puede escribir", "Ввод текста недоступен", "Tippen nicht verfügbar", "Saisie indisponible"),
    "keyboard.unsupported.message": ("This TV doesn’t accept text from the phone. Use the arrow buttons with the TV’s on‑screen keyboard.", "Esta TV no acepta texto del teléfono. Usa las flechas con el teclado en pantalla de la TV.", "Этот телевизор не принимает текст с телефона. Используйте стрелки и экранную клавиатуру телевизора.", "Dieser Fernseher nimmt keinen Text vom Telefon an. Nutze die Pfeiltasten mit der Bildschirmtastatur.", "Ce téléviseur n’accepte pas le texte du téléphone. Utilisez les flèches avec son clavier à l’écran."),
    "keyboard.useButtons": ("Use the buttons", "Usar los botones", "Использовать кнопки", "Tasten verwenden", "Utiliser les touches"),

    # Apps
    "apps.title": ("TV apps", "Apps de la TV", "Приложения ТВ", "TV-Apps", "Apps du téléviseur"),
    "apps.favorites": ("Quick launch", "Acceso rápido", "Быстрый запуск", "Schnellstart", "Lancement rapide"),
    "apps.favorites.footer": ("Tap Reorder to change the order. Star apps below to add them.", "Toca Reordenar para cambiar el orden. Marca apps con la estrella para añadirlas.", "Нажмите «Порядок», чтобы изменить порядок. Отметьте приложения звёздочкой, чтобы добавить.", "Tippe auf „Sortieren“, um die Reihenfolge zu ändern. Markiere Apps mit dem Stern, um sie hinzuzufügen.", "Touchez Réorganiser pour changer l’ordre. Ajoutez des apps avec l’étoile."),
    "apps.all": ("All apps", "Todas las apps", "Все приложения", "Alle Apps", "Toutes les apps"),
    "apps.reorder": ("Reorder", "Reordenar", "Порядок", "Sortieren", "Réorganiser"),
    "apps.installed": ("Installed on the TV", "Instaladas en la TV", "Установлены на ТВ", "Auf dem Fernseher installiert", "Installées sur le téléviseur"),
    "apps.installed.footer": ("List reported by your TV.", "Lista proporcionada por tu TV.", "Список получен от телевизора.", "Von deinem Fernseher gemeldete Liste.", "Liste fournie par votre téléviseur."),
    "apps.catalog": ("Catalog", "Catálogo", "Каталог", "Katalog", "Catalogue"),
    "apps.catalog.footer": ("Your TV doesn’t report installed apps. These are common services — they open only if installed on the TV.", "Tu TV no informa de sus apps. Son servicios habituales: solo se abren si están instalados en la TV.", "Телевизор не сообщает установленные приложения. Это популярные сервисы — они откроются, только если установлены на ТВ.", "Dein Fernseher meldet keine installierten Apps. Das sind gängige Dienste – sie öffnen sich nur, wenn sie installiert sind.", "Votre téléviseur n’indique pas ses apps. Ce sont des services courants : ils s’ouvrent seulement s’ils sont installés."),
    "apps.catalogNote": ("Catalog shortcuts open only if the app is installed on the TV.", "Los accesos del catálogo solo se abren si la app está instalada en la TV.", "Ярлыки каталога откроются, только если приложение установлено на ТВ.", "Katalog-Verknüpfungen öffnen sich nur, wenn die App installiert ist.", "Les raccourcis du catalogue s’ouvrent seulement si l’app est installée."),
    "apps.notConnected.title": ("No TV connected", "No hay TV conectada", "Телевизор не подключён", "Kein Fernseher verbunden", "Aucun téléviseur connecté"),
    "apps.notConnected.message": ("Connect your TV to open its apps.", "Conecta tu TV para abrir sus apps.", "Подключите телевизор, чтобы открыть его приложения.", "Verbinde deinen Fernseher, um seine Apps zu öffnen.", "Connectez votre téléviseur pour ouvrir ses apps."),
    "apps.favorite": ("Add %@ to quick launch", "Añadir %@ al acceso rápido", "Добавить %@ в быстрый запуск", "%@ zum Schnellstart hinzufügen", "Ajouter %@ au lancement rapide"),
    "apps.unfavorite": ("Remove %@ from quick launch", "Quitar %@ del acceso rápido", "Убрать %@ из быстрого запуска", "%@ aus Schnellstart entfernen", "Retirer %@ du lancement rapide"),
    "apps.open.accessibility": ("Open %@ on the TV", "Abrir %@ en la TV", "Открыть %@ на ТВ", "%@ auf dem Fernseher öffnen", "Ouvrir %@ sur le téléviseur"),
    "apps.status.opened": ("%@ is open on the TV.", "%@ está abierta en la TV.", "%@ открыто на телевизоре.", "%@ ist auf dem Fernseher geöffnet.", "%@ est ouvert sur le téléviseur."),
    "apps.status.sent": ("Request to open %@ sent. Check the TV.", "Solicitud para abrir %@ enviada. Revisa la TV.", "Команда открыть %@ отправлена. Проверьте телевизор.", "Anfrage zum Öffnen von %@ gesendet. Prüfe den Fernseher.", "Demande d’ouverture de %@ envoyée. Vérifiez le téléviseur."),
    "apps.status.failed": ("Couldn’t open %@.", "No se pudo abrir %@.", "Не удалось открыть %@.", "%@ konnte nicht geöffnet werden.", "Impossible d’ouvrir %@."),
    "apps.openHome": ("Go to TV Home", "Ir al inicio de la TV", "На главный экран ТВ", "Zum TV-Startbildschirm", "Aller à l’accueil du téléviseur"),

    # Saved TVs
    "saved.empty.title": ("No saved TVs", "No hay TV guardadas", "Нет сохранённых ТВ", "Keine gespeicherten Fernseher", "Aucun téléviseur enregistré"),
    "saved.empty.message": ("TVs you connect to appear here.", "Aquí aparecen las TV a las que te conectas.", "Здесь появятся телевизоры, к которым вы подключались.", "Hier erscheinen Fernseher, mit denen du dich verbindest.", "Les téléviseurs connectés apparaissent ici."),
    "saved.current": ("Current", "Actual", "Текущий", "Aktuell", "Actuel"),
    "saved.use": ("Use this TV", "Usar esta TV", "Использовать этот ТВ", "Diesen Fernseher nutzen", "Utiliser ce téléviseur"),
    "saved.rename": ("Rename", "Renombrar", "Переименовать", "Umbenennen", "Renommer"),
    "saved.rename.title": ("Rename TV", "Renombrar TV", "Переименовать ТВ", "Fernseher umbenennen", "Renommer le téléviseur"),
    "saved.rename.message": ("Changes the name only in this app, not on the TV.", "Cambia el nombre solo en esta app, no en la TV.", "Имя изменится только в приложении, не на телевизоре.", "Ändert den Namen nur in dieser App, nicht am Fernseher.", "Modifie le nom uniquement dans cette app, pas sur le téléviseur."),
    "saved.rename.placeholder": ("TV name", "Nombre de la TV", "Название ТВ", "Name des Fernsehers", "Nom du téléviseur"),
    "saved.reportedName": ("Name on the TV: %@", "Nombre en la TV: %@", "Имя на телевизоре: %@", "Name am Fernseher: %@", "Nom sur le téléviseur : %@"),
    "saved.forget": ("Forget", "Olvidar", "Забыть", "Vergessen", "Oublier"),
    "saved.forget.title": ("Forget this TV?", "¿Olvidar esta TV?", "Забыть этот телевизор?", "Diesen Fernseher vergessen?", "Oublier ce téléviseur ?"),
    "saved.forget.message": ("Its pairing data and favorites are removed from this iPhone. You can pair it again any time.", "Se eliminan de este iPhone sus datos de vinculación y favoritos. Puedes volver a vincularla cuando quieras.", "Данные сопряжения и избранное будут удалены с iPhone. Подключить телевизор снова можно в любой момент.", "Kopplungsdaten und Favoriten werden von diesem iPhone entfernt. Du kannst ihn jederzeit neu koppeln.", "Ses données d’association et favoris sont supprimés de cet iPhone. Vous pourrez l’associer à nouveau."),
}

PLURALS = {
    "diagnostic.remote.remaining.short": {
        "en": {"one": "Free check: %lld s left", "other": "Free check: %lld s left"},
        "es": {"one": "Prueba gratis: queda %lld s", "other": "Prueba gratis: quedan %lld s"},
        "ru": {"one": "Бесплатно: осталась %lld с", "few": "Бесплатно: осталось %lld с", "many": "Бесплатно: осталось %lld с", "other": "Бесплатно: осталось %lld с"},
        "de": {"one": "Gratis-Test: noch %lld s", "other": "Gratis-Test: noch %lld s"},
        "fr": {"one": "Test gratuit : %lld s restante", "many": "Test gratuit : %lld s restantes", "other": "Test gratuit : %lld s restantes"},
    },
    "diagnostic.remote.remaining": {
        "en": {"one": "Free check: %lld second left on this TV", "other": "Free check: %lld seconds left on this TV"},
        "es": {"one": "Comprobación gratuita: queda %lld segundo en esta TV", "other": "Comprobación gratuita: quedan %lld segundos en esta TV"},
        "ru": {"one": "Бесплатная проверка: осталась %lld секунда на этом ТВ", "few": "Бесплатная проверка: осталось %lld секунды на этом ТВ",
               "many": "Бесплатная проверка: осталось %lld секунд на этом ТВ", "other": "Бесплатная проверка: осталось %lld секунды на этом ТВ"},
        "de": {"one": "Kostenloser Test: noch %lld Sekunde auf diesem Fernseher", "other": "Kostenloser Test: noch %lld Sekunden auf diesem Fernseher"},
        "fr": {"one": "Vérification gratuite : %lld seconde restante sur ce téléviseur", "many": "Vérification gratuite : %lld secondes restantes sur ce téléviseur",
               "other": "Vérification gratuite : %lld secondes restantes sur ce téléviseur"},
    },
}
