# Localization source: onboarding pages, Settings banner and groups, notification states,
# redesigned support form and paywall additions.
# Tuple order: (en, es, ru, de, fr).
# NOTE: payment and legal wording requires review by a native editor before release.

STRINGS = {
    # Onboarding
    "onboarding.skip": ("Skip", "Omitir", "Пропустить", "Überspringen", "Passer"),
    "onboarding.next": ("Next", "Siguiente", "Далее", "Weiter", "Suivant"),
    "onboarding.connect": ("Connect TV", "Conectar la TV", "Подключить телевизор", "Fernseher verbinden", "Connecter le téléviseur"),
    "onboarding.step": ("Step %1$lld of %2$lld", "Paso %1$lld de %2$lld", "Шаг %1$lld из %2$lld", "Schritt %1$lld von %2$lld", "Étape %1$lld sur %2$lld"),
    "onboarding.page1.title": ("Your TV. One remote.", "Tu TV. Un solo mando.", "Ваш телевизор. Один пульт.", "Dein Fernseher. Eine Fernbedienung.", "Votre téléviseur. Une télécommande."),
    "onboarding.page1.subtitle": ("Buttons, volume, typing and TV apps — on your iPhone, over your Wi‑Fi.",
                                  "Botones, volumen, escritura y apps de la TV, en tu iPhone y por tu Wi‑Fi.",
                                  "Кнопки, громкость, ввод текста и приложения ТВ — на вашем iPhone через Wi‑Fi.",
                                  "Tasten, Lautstärke, Texteingabe und TV-Apps – auf deinem iPhone, über dein WLAN.",
                                  "Touches, volume, saisie et apps du téléviseur, sur votre iPhone via le Wi‑Fi."),
    "onboarding.page2.title": ("Favorite apps in one tap.", "Tus apps favoritas en un toque.", "Любимые приложения — одним касанием.", "Lieblings-Apps mit einem Tippen.", "Vos apps préférées en un geste."),
    "onboarding.page2.subtitle": ("Open apps installed on your TV right from your iPhone. What’s available depends on your TV model.",
                                  "Abre apps instaladas en tu TV desde el iPhone. Lo disponible depende del modelo de TV.",
                                  "Открывайте установленные на телевизоре приложения прямо с iPhone. Набор зависит от модели ТВ.",
                                  "Öffne auf dem Fernseher installierte Apps direkt vom iPhone. Was verfügbar ist, hängt vom TV-Modell ab.",
                                  "Ouvrez les apps installées sur votre téléviseur depuis l’iPhone. La disponibilité dépend du modèle."),
    "onboarding.page3.title": ("Show more on the big screen.", "Muestra más en la pantalla grande.", "Показывайте больше на большом экране.", "Zeig mehr auf dem großen Bildschirm.", "Montrez plus sur grand écran."),
    "onboarding.page3.subtitle": ("Share photos, videos and your screen with a compatible TV. We’ll check what your TV supports — for free.",
                                  "Comparte fotos, vídeos y tu pantalla con una TV compatible. Comprobaremos gratis qué admite tu TV.",
                                  "Показывайте фото, видео и экран на совместимом телевизоре. Мы бесплатно проверим, что поддерживает ваш ТВ.",
                                  "Teile Fotos, Videos und deinen Bildschirm mit einem kompatiblen Fernseher. Wir prüfen kostenlos, was er kann.",
                                  "Partagez photos, vidéos et votre écran avec un téléviseur compatible. Nous vérifions gratuitement ce qu’il prend en charge."),
    "discovery.continueWith": ("Continue with “%@”", "Continuar con «%@»", "Продолжить с «%@»", "Weiter mit „%@“", "Continuer avec « %@ »"),
    "help.introduction": ("View introduction", "Ver la introducción", "Посмотреть введение", "Einführung ansehen", "Revoir la présentation"),
    "platform.unknown": ("Other TV", "Otra TV", "Другой ТВ", "Anderer Fernseher", "Autre téléviseur"),

    # Settings
    "settings.group.app": ("App", "App", "Приложение", "App", "App"),
    "settings.group.privacy": ("Notifications and privacy", "Notificaciones y privacidad", "Уведомления и конфиденциальность", "Mitteilungen und Datenschutz", "Notifications et confidentialité"),
    "settings.group.help": ("Help", "Ayuda", "Помощь", "Hilfe", "Aide"),
    "settings.group.about": ("About and legal", "Información y legal", "О приложении и правовая информация", "Info und Rechtliches", "Infos et mentions légales"),
    "settings.versionLine": ("Version %@", "Versión %@", "Версия %@", "Version %@", "Version %@"),
    "notifications.summary.off": ("Off in iOS", "Desactivadas en iOS", "Выкл. в iOS", "In iOS aus", "Désactivées dans iOS"),
    "notifications.summary.none": ("None", "Ninguna", "Нет", "Keine", "Aucune"),
    "notifications.summary.count": ("%lld on", "Activas: %lld", "Вкл.: %lld", "%lld aktiv", "Activées : %lld"),
    "privacy.summary.sharing": ("Sharing", "Compartiendo", "Передача вкл.", "Teilen an", "Partage activé"),
    "privacy.summary.notSharing": ("Not sharing", "Sin compartir", "Без передачи", "Kein Teilen", "Aucun partage"),

    # Remote Pro banner
    "banner.pro.title": ("Remote Pro", "Remote Pro", "Remote Pro", "Remote Pro", "Remote Pro"),
    "banner.pro.pitch": ("Unlimited remote, keyboard, apps, photos and Screen Mirroring.",
                         "Mando sin límites, teclado, apps, fotos y duplicación de pantalla.",
                         "Пульт без ограничений, клавиатура, приложения, фото и трансляция экрана.",
                         "Unbegrenzte Fernbedienung, Tastatur, Apps, Fotos und Bildschirmspiegelung.",
                         "Télécommande illimitée, clavier, apps, photos et recopie de l’écran."),
    "banner.pro.seePlans": ("See plans", "Ver planes", "Посмотреть тарифы", "Tarife ansehen", "Voir les offres"),
    "banner.pro.billingIssue": ("There’s a problem with your payment. Update it in your Apple subscriptions to keep access.",
                                "Hay un problema con tu pago. Actualízalo en tus suscripciones de Apple para mantener el acceso.",
                                "Проблема с оплатой. Обновите способ оплаты в подписках Apple, чтобы сохранить доступ.",
                                "Es gibt ein Problem mit deiner Zahlung. Aktualisiere sie in deinen Apple-Abos, um den Zugriff zu behalten.",
                                "Un problème de paiement est survenu. Mettez-le à jour dans vos abonnements Apple pour garder l’accès."),
    "banner.pro.manageSubscription": ("Manage subscription", "Gestionar suscripción", "Управлять подпиской", "Abo verwalten", "Gérer l’abonnement"),
    "banner.pro.lifetime.title": ("Lifetime Access", "Acceso de por vida", "Доступ навсегда", "Dauerhafter Zugriff", "Accès à vie"),
    "banner.pro.lifetime.message": ("All features are unlocked. No recurring payments.", "Todas las funciones están desbloqueadas. Sin pagos recurrentes.",
                                    "Все функции открыты. Без регулярных платежей.", "Alle Funktionen sind freigeschaltet. Keine wiederkehrenden Zahlungen.",
                                    "Toutes les fonctions sont débloquées. Aucun paiement récurrent."),
    "banner.pro.lifetime.oldSubscription": ("All features are unlocked. Your old subscription still renews — turn off auto-renew to stop its payments.",
                                            "Todas las funciones están desbloqueadas. Tu suscripción anterior sigue renovándose: desactiva la renovación automática para detener sus pagos.",
                                            "Все функции открыты. Прежняя подписка ещё продлевается — отключите автопродление, чтобы остановить списания.",
                                            "Alle Funktionen sind freigeschaltet. Dein altes Abo verlängert sich noch – deaktiviere die automatische Verlängerung, um die Zahlungen zu stoppen.",
                                            "Toutes les fonctions sont débloquées. Votre ancien abonnement se renouvelle encore : désactivez le renouvellement automatique pour arrêter ses paiements."),
    "banner.pro.details": ("Details", "Detalles", "Подробнее", "Details", "Détails"),
    "banner.pro.trial.title": ("Free trial active", "Prueba gratuita activa", "Пробный период активен", "Kostenloser Test aktiv", "Essai gratuit actif"),
    "banner.pro.manageAccess": ("Manage access", "Gestionar acceso", "Управлять доступом", "Zugriff verwalten", "Gérer l’accès"),
    "banner.pro.plan.monthly": ("Remote Pro · Monthly", "Remote Pro · Mensual", "Remote Pro · Месяц", "Remote Pro · Monatlich", "Remote Pro · Mensuel"),
    "banner.pro.plan.yearly": ("Remote Pro · Yearly", "Remote Pro · Anual", "Remote Pro · Год", "Remote Pro · Jährlich", "Remote Pro · Annuel"),
    "banner.pro.plan.lifetime": ("Remote Pro · Lifetime", "Remote Pro · De por vida", "Remote Pro · Навсегда", "Remote Pro · Dauerhaft", "Remote Pro · À vie"),
    "banner.pro.renews": ("Renews on %@.", "Se renueva el %@.", "Продление %@.", "Verlängert sich am %@.", "Renouvellement le %@."),

    # Notifications
    "notifications.group.reminders": ("Reminders", "Recordatorios", "Напоминания", "Erinnerungen", "Rappels"),
    "notifications.group.remote": ("Messages from us", "Mensajes nuestros", "Сообщения от нас", "Nachrichten von uns", "Nos messages"),
    "notifications.trial.detail": ("Arrives while there’s still time to cancel. Scheduled on this iPhone.",
                                   "Llega cuando aún hay tiempo para cancelar. Se programa en este iPhone.",
                                   "Придёт, пока ещё можно отменить. Планируется на этом iPhone.",
                                   "Kommt, solange du noch kündigen kannst. Wird auf diesem iPhone geplant.",
                                   "Arrive quand il est encore temps d’annuler. Programmé sur cet iPhone."),
    "notifications.service.detail": ("Important app news, such as fixes for your TV model.", "Novedades importantes de la app, como correcciones para tu modelo de TV.",
                                     "Важные новости приложения, например исправления для вашей модели ТВ.", "Wichtige App-Neuigkeiten, etwa Korrekturen für dein TV-Modell.",
                                     "Nouveautés importantes de l’app, comme des correctifs pour votre modèle de téléviseur."),
    "notifications.marketing.detail": ("Occasional offers and discounts. Off unless you turn it on.", "Ofertas y descuentos ocasionales. Desactivado salvo que lo actives.",
                                       "Иногда — предложения и скидки. Выключено, пока вы не включите.", "Gelegentliche Angebote und Rabatte. Aus, bis du es einschaltest.",
                                       "Offres et réductions occasionnelles. Désactivé tant que vous ne l’activez pas."),
    "notifications.prompt.title": ("Allow notifications?", "¿Permitir notificaciones?", "Разрешить уведомления?", "Mitteilungen erlauben?", "Autoriser les notifications ?"),
    "notifications.prompt.message": ("iOS will ask for permission next. You choose each category here and can turn it off at any time.",
                                     "A continuación iOS pedirá permiso. Tú eliges cada categoría aquí y puedes desactivarla cuando quieras.",
                                     "Далее iOS запросит разрешение. Каждую категорию вы выбираете здесь и можете отключить в любой момент.",
                                     "Als Nächstes fragt iOS nach der Erlaubnis. Jede Kategorie wählst du hier und kannst sie jederzeit ausschalten.",
                                     "iOS va ensuite demander l’autorisation. Vous choisissez chaque catégorie ici et pouvez la désactiver à tout moment."),
    "notifications.prompt.continue": ("Continue", "Continuar", "Продолжить", "Weiter", "Continuer"),
    "notifications.status.allowed": ("Notifications are allowed for this app.", "Las notificaciones están permitidas para esta app.", "Уведомления для приложения разрешены.",
                                     "Mitteilungen sind für diese App erlaubt.", "Les notifications sont autorisées pour cette app."),
    "notifications.status.provisional": ("Delivered quietly to Notification Center. You can allow banners in iOS Settings.",
                                         "Se entregan en silencio al Centro de notificaciones. Puedes permitir avisos en Ajustes de iOS.",
                                         "Доставляются без звука в Центр уведомлений. Баннеры можно разрешить в настройках iOS.",
                                         "Werden still in die Mitteilungszentrale zugestellt. Banner kannst du in den iOS-Einstellungen erlauben.",
                                         "Livrées discrètement dans le centre de notifications. Vous pouvez autoriser les bannières dans les réglages iOS."),
    "notifications.status.notAsked": ("iOS will ask for permission when you turn on the first category.", "iOS pedirá permiso cuando actives la primera categoría.",
                                      "iOS запросит разрешение, когда вы включите первую категорию.", "iOS fragt nach der Erlaubnis, wenn du die erste Kategorie einschaltest.",
                                      "iOS demandera l’autorisation lorsque vous activerez la première catégorie."),
    "notifications.status.denied.title": ("Notifications are off in iOS Settings", "Las notificaciones están desactivadas en Ajustes de iOS", "Уведомления выключены в настройках iOS",
                                          "Mitteilungen sind in den iOS-Einstellungen aus", "Les notifications sont désactivées dans les réglages iOS"),
    "notifications.status.denied.message": ("To get reminders, allow notifications for TV Remote in Settings, then come back — this screen updates automatically.",
                                            "Para recibir recordatorios, permite las notificaciones de TV Remote en Ajustes y vuelve: esta pantalla se actualiza sola.",
                                            "Чтобы получать напоминания, разрешите уведомления для TV Remote в Настройках и вернитесь — экран обновится сам.",
                                            "Für Erinnerungen erlaube Mitteilungen für TV Remote in den Einstellungen und kehre zurück – dieser Bildschirm aktualisiert sich automatisch.",
                                            "Pour recevoir des rappels, autorisez les notifications de TV Remote dans Réglages, puis revenez : cet écran se met à jour automatiquement."),
    "notifications.sync.syncing": ("Saving your choice…", "Guardando tu elección…", "Сохраняем выбор…", "Auswahl wird gespeichert …", "Enregistrement de votre choix…"),
    "notifications.sync.notConfigured": ("Your choice is saved on this iPhone. Messages from us aren’t set up in this build yet, so only the trial reminder can arrive.",
                                         "Tu elección se guarda en este iPhone. Nuestros mensajes aún no están configurados en esta versión, así que solo puede llegar el recordatorio de la prueba.",
                                         "Выбор сохранён на этом iPhone. Сообщения от нас в этой сборке ещё не настроены, поэтому может прийти только напоминание о пробном периоде.",
                                         "Deine Auswahl ist auf diesem iPhone gespeichert. Nachrichten von uns sind in dieser Version noch nicht eingerichtet, daher kann nur die Test-Erinnerung ankommen.",
                                         "Votre choix est enregistré sur cet iPhone. Nos messages ne sont pas encore configurés dans cette version : seul le rappel d’essai peut arriver."),
    "notifications.sync.pending": ("Your choice is saved and will sync when you’re online.", "Tu elección está guardada y se sincronizará cuando tengas conexión.",
                                   "Выбор сохранён и синхронизируется, когда появится интернет.", "Deine Auswahl ist gespeichert und wird synchronisiert, sobald du online bist.",
                                   "Votre choix est enregistré et sera synchronisé dès que vous serez en ligne."),
    "notifications.sync.failed": ("Couldn’t update your message subscription. Your choice is saved — try again.",
                                  "No se pudo actualizar tu suscripción a mensajes. Tu elección está guardada; inténtalo de nuevo.",
                                  "Не удалось обновить подписку на сообщения. Выбор сохранён — попробуйте ещё раз.",
                                  "Dein Nachrichten-Abo konnte nicht aktualisiert werden. Deine Auswahl ist gespeichert – versuche es erneut.",
                                  "Impossible de mettre à jour votre abonnement aux messages. Votre choix est enregistré : réessayez."),

    # Support form
    "support.intro": ("Tell us what happened. The app prepares your message — you review and send it yourself in Mail or the web form.",
                      "Cuéntanos qué pasó. La app prepara tu mensaje; tú lo revisas y lo envías en Mail o en el formulario web.",
                      "Расскажите, что произошло. Приложение подготовит сообщение — вы проверите и отправите его сами в Почте или веб-форме.",
                      "Beschreibe, was passiert ist. Die App bereitet deine Nachricht vor – du prüfst und sendest sie selbst in Mail oder im Webformular.",
                      "Dites-nous ce qui s’est passé. L’app prépare votre message : vous le relisez et l’envoyez vous-même dans Mail ou le formulaire web."),
    "support.field.problem.required": ("Required to continue.", "Obligatorio para continuar.", "Обязательно для продолжения.", "Erforderlich, um fortzufahren.", "Obligatoire pour continuer."),
    "support.field.contactEmail": ("Email for a reply (optional)", "Correo para responderte (opcional)", "Email для ответа (необязательно)", "E-Mail für die Antwort (optional)", "E-mail pour la réponse (facultatif)"),
    "support.field.contactEmail.placeholder": ("name@example.com", "nombre@example.com", "name@example.com", "name@example.com", "nom@example.com"),
    "support.field.contactEmail.footer": ("Only needed for the web form. It’s added to your message and used only to reply.",
                                          "Solo hace falta para el formulario web. Se añade al mensaje y solo se usa para responderte.",
                                          "Нужен только для веб-формы. Добавляется в сообщение и используется только для ответа.",
                                          "Nur für das Webformular nötig. Wird der Nachricht hinzugefügt und nur für die Antwort verwendet.",
                                          "Utile seulement pour le formulaire web. Ajoutée au message et utilisée uniquement pour vous répondre."),
    "support.field.contactEmail.invalid": ("Check the email address.", "Revisa la dirección de correo.", "Проверьте адрес электронной почты.", "Prüfe die E-Mail-Adresse.", "Vérifiez l’adresse e-mail."),
    "support.screenshot.title": ("Screenshot", "Captura de pantalla", "Скриншот", "Bildschirmfoto", "Capture d’écran"),
    "support.diagnostics.detail": ("Helps us find the cause faster.", "Nos ayuda a encontrar la causa más rápido.", "Помогает быстрее найти причину.", "Hilft uns, die Ursache schneller zu finden.", "Nous aide à trouver la cause plus vite."),
    "support.channel.title": ("How to send", "Cómo enviarlo", "Способ отправки", "Versandweg", "Mode d’envoi"),
    "support.channel.option.email": ("Email", "Correo", "Почта", "E-Mail", "E-mail"),
    "support.channel.option.form": ("Web form", "Formulario web", "Веб-форма", "Webformular", "Formulaire web"),
    "support.primary.email": ("Prepare email", "Preparar correo", "Подготовить письмо", "E-Mail vorbereiten", "Préparer l’e-mail"),
    "support.primary.form": ("Open form", "Abrir formulario", "Открыть форму", "Formular öffnen", "Ouvrir le formulaire"),
    "support.more": ("More options", "Más opciones", "Другие действия", "Weitere Optionen", "Autres options"),
    "support.deleteDraft.confirm": ("Delete this draft? The text and attached screenshot will be removed from this iPhone.",
                                    "¿Eliminar este borrador? El texto y la captura adjunta se borrarán de este iPhone.",
                                    "Удалить черновик? Текст и приложенный скриншот будут удалены с этого iPhone.",
                                    "Diesen Entwurf löschen? Text und angehängtes Bildschirmfoto werden von diesem iPhone entfernt.",
                                    "Supprimer ce brouillon ? Le texte et la capture jointe seront effacés de cet iPhone."),
    "support.mail.saved": ("Saved to Drafts in Mail. It hasn’t been sent.", "Guardado en Borradores de Mail. No se ha enviado.", "Сохранено в черновиках Почты. Письмо не отправлено.",
                           "In Mail unter Entwürfe gesichert. Nicht gesendet.", "Enregistré dans les brouillons de Mail. Non envoyé."),
    "support.mail.failed": ("Mail couldn’t prepare the message. Copy the text and send it from another app.", "Mail no pudo preparar el mensaje. Copia el texto y envíalo desde otra app.",
                            "Почта не смогла подготовить письмо. Скопируйте текст и отправьте из другого приложения.",
                            "Mail konnte die Nachricht nicht vorbereiten. Kopiere den Text und sende ihn aus einer anderen App.",
                            "Mail n’a pas pu préparer le message. Copiez le texte et envoyez-le depuis une autre app."),
    "support.mail.external": ("Your mail app opened with the message. It’s sent only when you send it there.",
                              "Tu app de correo se abrió con el mensaje. Solo se envía cuando lo envías desde allí.",
                              "Почтовое приложение открыто с готовым письмом. Оно уйдёт, только когда вы отправите его там.",
                              "Deine Mail-App wurde mit der Nachricht geöffnet. Gesendet wird erst, wenn du sie dort sendest.",
                              "Votre app de messagerie s’est ouverte avec le message. Il n’est envoyé que lorsque vous l’envoyez depuis celle-ci."),
    "support.form.returned": ("We can’t see whether the form was submitted. If you didn’t submit it, your text is still copied.",
                              "No podemos saber si se envió el formulario. Si no lo enviaste, tu texto sigue copiado.",
                              "Мы не видим, была ли отправлена форма. Если вы её не отправили, текст всё ещё скопирован.",
                              "Wir sehen nicht, ob das Formular gesendet wurde. Falls nicht, ist dein Text noch kopiert.",
                              "Nous ne pouvons pas savoir si le formulaire a été envoyé. Sinon, votre texte est toujours copié."),

    # Bonus
    "bonus.notEligible.title": ("Welcome bonus is for new customers", "El bono de bienvenida es para nuevos clientes", "Приветственный бонус — для новых пользователей", "Der Willkommensbonus ist für Neukunden", "Le bonus de bienvenue est réservé aux nouveaux clients"),
    "bonus.notEligible.message": ("You already have or had Remote Pro, so there’s nothing to claim here.", "Ya tienes o tuviste Remote Pro, así que aquí no hay nada que reclamar.", "У вас уже есть или был Remote Pro, поэтому здесь нечего получать.", "Du hast oder hattest bereits Remote Pro, daher gibt es hier nichts einzulösen.", "Vous avez ou avez eu Remote Pro : il n’y a rien à récupérer ici."),
    "bonus.networkError": ("Couldn’t check available bonuses. Check your connection.", "No se pudieron comprobar los bonos. Revisa la conexión.", "Не удалось проверить доступные бонусы. Проверьте подключение.", "Boni konnten nicht geprüft werden. Prüfe die Verbindung.", "Impossible de vérifier les bonus. Vérifiez la connexion."),

    "support.screenshot.failed": ("Couldn’t attach this screenshot. Try another one.", "No se pudo adjuntar esta captura. Prueba con otra.", "Не удалось приложить скриншот. Попробуйте другой.", "Dieses Bildschirmfoto konnte nicht angehängt werden. Versuche ein anderes.", "Impossible de joindre cette capture. Essayez-en une autre."),
    "support.screenshot.notSent": ("The web form can’t take the screenshot from here — add it in the form if it allows files.", "El formulario web no puede recibir la captura desde aquí; añádela en el formulario si admite archivos.", "Веб-форма не может получить скриншот отсюда — приложите его в форме, если она принимает файлы.", "Das Webformular kann das Bildschirmfoto nicht von hier übernehmen – füge es im Formular hinzu, falls möglich.", "Le formulaire web ne peut pas recevoir la capture d’ici : ajoutez-la dans le formulaire s’il accepte des fichiers."),
    "support.mail.external.noScreenshot": ("Your mail app opened with the message. The screenshot couldn’t be attached — add it there if needed.", "Tu app de correo se abrió con el mensaje. No se pudo adjuntar la captura; añádela allí si hace falta.", "Почтовое приложение открыто с письмом. Скриншот приложить не удалось — добавьте его там при необходимости.", "Deine Mail-App wurde mit der Nachricht geöffnet. Das Bildschirmfoto konnte nicht angehängt werden – füge es dort hinzu.", "Votre app de messagerie s’est ouverte avec le message. La capture n’a pas pu être jointe : ajoutez-la si besoin."),

    "privacy.clearDiagnostics.confirm": ("Clear the technical log on this iPhone? It can’t be restored.", "¿Borrar el registro técnico de este iPhone? No se puede recuperar.", "Очистить технический журнал на этом iPhone? Восстановить его не получится.", "Technisches Protokoll auf diesem iPhone löschen? Es lässt sich nicht wiederherstellen.", "Effacer le journal technique de cet iPhone ? Il ne pourra pas être restauré."),
    "privacy.clearDiagnostics.done": ("Technical log cleared.", "Registro técnico borrado.", "Технический журнал очищен.", "Technisches Protokoll gelöscht.", "Journal technique effacé."),

    # Paywall additions
    "paywall.benefit.photosMirroring": ("Photos, videos and Screen Mirroring on supported TVs", "Fotos, vídeos y duplicación de pantalla en TV compatibles",
                                        "Фото, видео и трансляция экрана на поддерживаемых ТВ", "Fotos, Videos und Bildschirmspiegelung auf unterstützten Fernsehern",
                                        "Photos, vidéos et recopie de l’écran sur les téléviseurs compatibles"),
    "paywall.bonus.waiting": ("Your welcome bonus is waiting.", "Tu bono de bienvenida te espera.", "Ваш приветственный бонус ждёт.", "Dein Willkommensbonus wartet.", "Votre bonus de bienvenue vous attend."),
    "paywall.bonus.open": ("Open", "Abrir", "Открыть", "Öffnen", "Ouvrir"),
    "paywall.period.year": ("per year", "al año", "в год", "pro Jahr", "par an"),
    "paywall.period.month": ("per month", "al mes", "в месяц", "pro Monat", "par mois"),
    "paywall.period.once": ("one-time", "pago único", "один раз", "einmalig", "paiement unique"),
    # Under the purchase button: 1–2 lines at caption2. Full terms are in "paywall.terms.full".
    "paywall.note.trial.short": ("%1$@ free, then %2$@ from %3$@. Auto-renews until canceled.",
                                 "%1$@ gratis, luego %2$@ desde el %3$@. Se renueva hasta que canceles.",
                                 "%1$@ бесплатно, с %3$@ — %2$@. Автопродление до отмены.",
                                 "%1$@ kostenlos, dann %2$@ ab %3$@. Verlängert sich bis zur Kündigung.",
                                 "%1$@ gratuits, puis %2$@ dès le %3$@. Renouvellement jusqu’à résiliation."),
    "paywall.note.subscription.short": ("%@. Auto-renews until canceled.", "%@. Se renueva hasta que canceles.", "%@. Автопродление до отмены.",
                                        "%@. Verlängert sich bis zur Kündigung.", "%@. Renouvellement jusqu’à résiliation."),
    "paywall.terms.full": ("Payment is charged to your Apple Account when you confirm. Subscriptions renew automatically unless canceled at least 24 hours before the end of the current period or free trial. Manage or cancel them in your Apple subscriptions.",
                           "El pago se carga a tu cuenta de Apple al confirmar. Las suscripciones se renuevan automáticamente salvo que las canceles al menos 24 horas antes del final del periodo actual o de la prueba gratuita. Gestiónalas o cancélalas en tus suscripciones de Apple.",
                           "Оплата списывается с Apple Account при подтверждении. Подписка продлевается автоматически, если не отменить её минимум за 24 часа до конца текущего или пробного периода. Управлять подпиской и отменить её можно в подписках Apple.",
                           "Die Zahlung wird bei Bestätigung deinem Apple Account belastet. Abos verlängern sich automatisch, sofern sie nicht mindestens 24 Stunden vor Ende des aktuellen Zeitraums oder Tests gekündigt werden. Verwalten oder kündigen kannst du sie in deinen Apple-Abos.",
                           "Le paiement est débité de votre compte Apple à la confirmation. Les abonnements se renouvellent automatiquement sauf résiliation au moins 24 heures avant la fin de la période en cours ou de l’essai gratuit. Gérez-les ou résiliez-les dans vos abonnements Apple."),
    "paywall.cta.lifetime.price": ("Buy for %@", "Comprar por %@", "Купить за %@", "Für %@ kaufen", "Acheter pour %@"),
}

PLURALS = {}
