# Localization source: errors, recovery actions, capabilities, remote keys.
# Tuple order: (en, es, ru, de, fr). English is the source and fallback language.
# Legal/payment wording must be reviewed by a native editor before release (see RELEASE_CHECKLIST.md).

STRINGS = {
    # --- Errors (title + message) -------------------------------------------------------
    "error.net-001.title": ("Local network access is off", "El acceso a la red local está desactivado", "Доступ к локальной сети выключен", "Zugriff auf das lokale Netzwerk ist aus", "L’accès au réseau local est désactivé"),
    "error.net-001.message": ("TV Remote needs Local Network access to find and control your TV. Turn it on in Settings → TV Remote, then search again.",
                              "TV Remote necesita acceso a la red local para encontrar y controlar tu TV. Actívalo en Ajustes → TV Remote y vuelve a buscar.",
                              "TV Remote нужен доступ к локальной сети, чтобы найти телевизор и управлять им. Включите его в Настройках → TV Remote и повторите поиск.",
                              "TV Remote braucht Zugriff auf das lokale Netzwerk, um deinen Fernseher zu finden und zu steuern. Aktiviere ihn unter Einstellungen → TV Remote und suche erneut.",
                              "TV Remote a besoin de l’accès au réseau local pour trouver et contrôler votre téléviseur. Activez-le dans Réglages → TV Remote, puis relancez la recherche."),
    "error.net-002.title": ("Not connected to Wi‑Fi", "Sin conexión Wi‑Fi", "Нет подключения к Wi‑Fi", "Nicht mit WLAN verbunden", "Pas de connexion Wi‑Fi"),
    "error.net-002.message": ("Connect your iPhone to the same Wi‑Fi network as your TV.",
                              "Conecta el iPhone a la misma red Wi‑Fi que tu TV.",
                              "Подключите iPhone к той же сети Wi‑Fi, что и телевизор.",
                              "Verbinde dein iPhone mit demselben WLAN wie deinen Fernseher.",
                              "Connectez votre iPhone au même réseau Wi‑Fi que votre téléviseur."),
    "error.net-003.title": ("No TVs found", "No se encontró ninguna TV", "Телевизоры не найдены", "Keine Fernseher gefunden", "Aucun téléviseur trouvé"),
    "error.net-003.message": ("Make sure the TV is on and on the same network. Guest networks and VPNs can hide devices from each other.",
                              "Comprueba que la TV esté encendida y en la misma red. Las redes de invitados y las VPN pueden ocultar los dispositivos entre sí.",
                              "Убедитесь, что телевизор включён и находится в той же сети. Гостевая сеть и VPN могут скрывать устройства друг от друга.",
                              "Stelle sicher, dass der Fernseher eingeschaltet und im selben Netzwerk ist. Gastnetzwerke und VPNs können Geräte voneinander verbergen.",
                              "Vérifiez que le téléviseur est allumé et sur le même réseau. Les réseaux invités et les VPN peuvent masquer les appareils entre eux."),
    "error.net-004.title": ("TV not reachable", "No se puede acceder a la TV", "Телевизор недоступен", "Fernseher nicht erreichbar", "Téléviseur injoignable"),
    "error.net-004.message": ("The TV didn’t respond. It may be off, in deep standby, or on another network.",
                              "La TV no respondió. Puede que esté apagada, en reposo profundo o en otra red.",
                              "Телевизор не ответил. Возможно, он выключен, в глубоком режиме ожидания или в другой сети.",
                              "Der Fernseher hat nicht geantwortet. Er ist eventuell aus, im tiefen Standby oder in einem anderen Netzwerk.",
                              "Le téléviseur n’a pas répondu. Il est peut-être éteint, en veille profonde ou sur un autre réseau."),
    "error.net-005.title": ("TV address changed", "La dirección de la TV cambió", "Адрес телевизора изменился", "Adresse des Fernsehers geändert", "L’adresse du téléviseur a changé"),
    "error.net-005.message": ("Your router gave the TV a new address. Search again — your saved settings and favorites are kept.",
                              "El router asignó una nueva dirección a la TV. Vuelve a buscar: tus ajustes y favoritos se conservan.",
                              "Роутер выдал телевизору новый адрес. Повторите поиск — сохранённые настройки и избранное останутся.",
                              "Dein Router hat dem Fernseher eine neue Adresse gegeben. Suche erneut – Einstellungen und Favoriten bleiben erhalten.",
                              "Votre routeur a attribué une nouvelle adresse au téléviseur. Relancez la recherche : vos réglages et favoris sont conservés."),
    "error.pair-001.title": ("Connection not allowed", "Conexión no permitida", "Подключение не разрешено", "Verbindung nicht erlaubt", "Connexion refusée"),
    "error.pair-001.message": ("The request was declined or closed on the TV. Try again and choose Allow on the TV screen.",
                               "La solicitud se rechazó o se cerró en la TV. Inténtalo de nuevo y elige Permitir en la pantalla de la TV.",
                               "Запрос отклонён или закрыт на телевизоре. Повторите попытку и выберите «Разрешить» на экране телевизора.",
                               "Die Anfrage wurde am Fernseher abgelehnt oder geschlossen. Versuche es erneut und wähle am Fernseher „Zulassen“.",
                               "La demande a été refusée ou fermée sur le téléviseur. Réessayez et choisissez Autoriser à l’écran."),
    "error.pair-002.title": ("No answer from the TV", "La TV no respondió", "Телевизор не ответил", "Keine Antwort vom Fernseher", "Aucune réponse du téléviseur"),
    "error.pair-002.message": ("The confirmation on the TV timed out. Keep the TV remote nearby and try again.",
                               "La confirmación en la TV caducó. Ten a mano el mando de la TV e inténtalo de nuevo.",
                               "Время подтверждения на телевизоре истекло. Держите пульт телевизора рядом и попробуйте снова.",
                               "Die Bestätigung am Fernseher ist abgelaufen. Halte die TV-Fernbedienung bereit und versuche es erneut.",
                               "La confirmation sur le téléviseur a expiré. Gardez la télécommande du téléviseur à portée de main et réessayez."),
    "error.pair-003.title": ("The code didn’t match", "El código no coincide", "Код не подошёл", "Der Code stimmt nicht", "Le code ne correspond pas"),
    "error.pair-003.message": ("Check the code shown on the TV and enter it again.",
                               "Revisa el código que aparece en la TV e introdúcelo de nuevo.",
                               "Проверьте код на экране телевизора и введите его снова.",
                               "Prüfe den Code auf dem Fernseher und gib ihn erneut ein.",
                               "Vérifiez le code affiché sur le téléviseur et saisissez-le à nouveau."),
    "error.pair-004.title": ("Pair the TV again", "Vuelve a vincular la TV", "Подключите телевизор заново", "Fernseher erneut koppeln", "Associez à nouveau le téléviseur"),
    "error.pair-004.message": ("The TV no longer accepts this iPhone, for example after an update or reset. Pair it once more.",
                               "La TV ya no acepta este iPhone, por ejemplo tras una actualización o un restablecimiento. Vincúlala otra vez.",
                               "Телевизор больше не принимает этот iPhone — например, после обновления или сброса. Подключите его ещё раз.",
                               "Der Fernseher akzeptiert dieses iPhone nicht mehr, z. B. nach einem Update oder Zurücksetzen. Kopple ihn erneut.",
                               "Le téléviseur n’accepte plus cet iPhone, par exemple après une mise à jour ou une réinitialisation. Associez-le à nouveau."),
    "error.pair-005.title": ("This TV model isn’t supported yet", "Este modelo de TV aún no es compatible", "Эта модель пока не поддерживается", "Dieses Modell wird noch nicht unterstützt", "Ce modèle n’est pas encore pris en charge"),
    "error.pair-005.message": ("The TV uses a pairing method we can’t complete. Contact support with the TV model so we can check it.",
                               "La TV usa un método de vinculación que no podemos completar. Contacta con soporte indicando el modelo para que lo revisemos.",
                               "Телевизор использует способ сопряжения, который мы не можем завершить. Напишите в поддержку и укажите модель — мы проверим.",
                               "Der Fernseher nutzt ein Kopplungsverfahren, das wir nicht abschließen können. Nenne dem Support das Modell, damit wir es prüfen.",
                               "Le téléviseur utilise une méthode d’association que nous ne pouvons pas terminer. Contactez l’assistance en indiquant le modèle."),
    "error.pair-006.title": ("TV identity changed", "La identidad de la TV cambió", "Изменилась идентификация телевизора", "Identität des Fernsehers geändert", "L’identité du téléviseur a changé"),
    "error.pair-006.message": ("For your security, pair again: the TV presented a different certificate than before.",
                               "Por seguridad, vuelve a vincularla: la TV presentó un certificado distinto al anterior.",
                               "В целях безопасности подключите телевизор заново: он предъявил другой сертификат, чем раньше.",
                               "Zu deiner Sicherheit bitte neu koppeln: Der Fernseher hat ein anderes Zertifikat als zuvor gezeigt.",
                               "Par sécurité, associez-le à nouveau : le téléviseur a présenté un certificat différent."),
    "error.ses-001.title": ("Connection lost", "Se perdió la conexión", "Связь потеряна", "Verbindung unterbrochen", "Connexion perdue"),
    "error.ses-001.message": ("The connection to the TV dropped. Check Wi‑Fi and reconnect.",
                              "Se interrumpió la conexión con la TV. Comprueba el Wi‑Fi y vuelve a conectar.",
                              "Соединение с телевизором прервалось. Проверьте Wi‑Fi и подключитесь снова.",
                              "Die Verbindung zum Fernseher ist abgebrochen. Prüfe das WLAN und verbinde erneut.",
                              "La connexion au téléviseur a été interrompue. Vérifiez le Wi‑Fi et reconnectez-vous."),
    "error.ses-002.title": ("Not available on this TV", "No disponible en esta TV", "Недоступно на этом телевизоре", "Auf diesem Fernseher nicht verfügbar", "Indisponible sur ce téléviseur"),
    "error.ses-002.message": ("This TV doesn’t accept that command. The other buttons still work.",
                              "Esta TV no acepta ese comando. Los demás botones siguen funcionando.",
                              "Телевизор не принимает эту команду. Остальные кнопки работают.",
                              "Dieser Fernseher akzeptiert diesen Befehl nicht. Die anderen Tasten funktionieren weiter.",
                              "Ce téléviseur n’accepte pas cette commande. Les autres touches fonctionnent toujours."),
    "error.ses-003.title": ("The TV didn’t respond in time", "La TV no respondió a tiempo", "Телевизор не ответил вовремя", "Der Fernseher hat nicht rechtzeitig reagiert", "Le téléviseur n’a pas répondu à temps"),
    "error.ses-003.message": ("The command may not have arrived. Check the TV and try again.",
                              "Puede que el comando no haya llegado. Revisa la TV e inténtalo de nuevo.",
                              "Команда могла не дойти. Проверьте телевизор и попробуйте снова.",
                              "Der Befehl ist eventuell nicht angekommen. Prüfe den Fernseher und versuche es erneut.",
                              "La commande n’est peut-être pas arrivée. Vérifiez le téléviseur et réessayez."),
    "error.txt-001.title": ("Select a text field on the TV", "Selecciona un campo de texto en la TV", "Выберите поле ввода на телевизоре", "Wähle ein Textfeld auf dem Fernseher", "Sélectionnez un champ de texte sur le téléviseur"),
    "error.txt-001.message": ("Open a search or text field on the TV first, then type again.",
                              "Primero abre un campo de búsqueda o de texto en la TV y vuelve a escribir.",
                              "Сначала откройте на телевизоре поле поиска или ввода, затем наберите текст снова.",
                              "Öffne zuerst ein Such- oder Textfeld am Fernseher und tippe dann erneut.",
                              "Ouvrez d’abord un champ de recherche ou de texte sur le téléviseur, puis saisissez à nouveau."),
    "error.txt-002.title": ("Typing isn’t supported here", "Aquí no se puede escribir", "Здесь нельзя вводить текст", "Tippen wird hier nicht unterstützt", "La saisie n’est pas prise en charge ici"),
    "error.txt-002.message": ("This TV or app doesn’t accept text from the phone. Use the arrow buttons to type on the TV keyboard.",
                              "Esta TV o app no acepta texto del teléfono. Usa las flechas para escribir con el teclado de la TV.",
                              "Этот телевизор или приложение не принимает текст с телефона. Используйте стрелки для ввода на клавиатуре телевизора.",
                              "Dieser Fernseher oder diese App nimmt keinen Text vom Telefon an. Nutze die Pfeiltasten für die TV-Tastatur.",
                              "Ce téléviseur ou cette app n’accepte pas le texte du téléphone. Utilisez les flèches pour saisir sur le clavier du téléviseur."),
    "error.txt-003.title": ("Not sure the text arrived", "No se sabe si llegó el texto", "Неизвестно, дошёл ли текст", "Unklar, ob der Text angekommen ist", "Impossible de confirmer l’envoi du texte"),
    "error.txt-003.message": ("Check the TV. If the text is missing, send it again — we don’t resend automatically to avoid duplicates.",
                              "Revisa la TV. Si falta el texto, envíalo de nuevo; no lo reenviamos automáticamente para evitar duplicados.",
                              "Проверьте телевизор. Если текста нет, отправьте его снова — мы не повторяем отправку сами, чтобы не было дублей.",
                              "Prüfe den Fernseher. Fehlt der Text, sende ihn erneut – wir senden nicht automatisch nach, um Doppelungen zu vermeiden.",
                              "Vérifiez le téléviseur. Si le texte manque, renvoyez-le : nous ne le renvoyons pas automatiquement pour éviter les doublons."),
    "error.app-001.title": ("App not found on the TV", "App no encontrada en la TV", "Приложение не найдено на телевизоре", "App nicht auf dem Fernseher gefunden", "App introuvable sur le téléviseur"),
    "error.app-001.message": ("The app may not be installed or available in your region. Install or check it on the TV itself.",
                              "Puede que la app no esté instalada o disponible en tu región. Instálala o revísala en la propia TV.",
                              "Возможно, приложение не установлено или недоступно в вашем регионе. Установите или проверьте его на самом телевизоре.",
                              "Die App ist eventuell nicht installiert oder in deiner Region nicht verfügbar. Installiere oder prüfe sie direkt am Fernseher.",
                              "L’app n’est peut-être pas installée ou disponible dans votre région. Installez-la ou vérifiez-la sur le téléviseur."),
    "error.app-002.title": ("Couldn’t open the app", "No se pudo abrir la app", "Не удалось открыть приложение", "App konnte nicht geöffnet werden", "Impossible d’ouvrir l’app"),
    "error.app-002.message": ("The TV didn’t accept the launch command. Try again or open it from the TV’s Home screen.",
                              "La TV no aceptó la orden de abrir. Inténtalo de nuevo o ábrela desde la pantalla de inicio de la TV.",
                              "Телевизор не принял команду запуска. Попробуйте снова или откройте приложение с главного экрана телевизора.",
                              "Der Fernseher hat den Startbefehl nicht angenommen. Versuche es erneut oder öffne die App über den Startbildschirm.",
                              "Le téléviseur n’a pas accepté la commande. Réessayez ou ouvrez l’app depuis l’écran d’accueil du téléviseur."),
    "error.app-003.title": ("App list unavailable", "Lista de apps no disponible", "Список приложений недоступен", "App-Liste nicht verfügbar", "Liste des apps indisponible"),
    "error.app-003.message": ("This TV doesn’t share its installed apps. You can still use the catalog buttons.",
                              "Esta TV no comparte sus apps instaladas. Puedes seguir usando los botones del catálogo.",
                              "Телевизор не сообщает список установленных приложений. Кнопки каталога по-прежнему доступны.",
                              "Dieser Fernseher teilt seine installierten Apps nicht. Die Katalog-Tasten kannst du weiterhin nutzen.",
                              "Ce téléviseur ne partage pas ses apps installées. Vous pouvez toujours utiliser les boutons du catalogue."),
    "error.med-001.title": ("TV can’t receive photos or videos", "La TV no puede recibir fotos ni vídeos", "Телевизор не принимает фото и видео", "Fernseher kann keine Fotos oder Videos empfangen", "Le téléviseur ne peut pas recevoir de photos ou vidéos"),
    "error.med-001.message": ("We couldn’t find a media receiver on this TV. Some TVs need media sharing (DLNA) turned on in their settings.",
                              "No encontramos un receptor multimedia en esta TV. Algunas TV requieren activar el uso compartido (DLNA) en sus ajustes.",
                              "На этом телевизоре не найден медиаприёмник. На некоторых моделях нужно включить общий доступ к медиа (DLNA) в настройках.",
                              "Auf diesem Fernseher wurde kein Medienempfänger gefunden. Bei manchen Modellen muss die Medienfreigabe (DLNA) aktiviert werden.",
                              "Aucun récepteur multimédia trouvé sur ce téléviseur. Certains modèles exigent d’activer le partage multimédia (DLNA)."),
    "error.med-002.title": ("Format not supported", "Formato no compatible", "Формат не поддерживается", "Format nicht unterstützt", "Format non pris en charge"),
    "error.med-002.message": ("The TV can’t play this file. Try another photo or a video recorded on iPhone.",
                              "La TV no puede reproducir este archivo. Prueba con otra foto o con un vídeo grabado con el iPhone.",
                              "Телевизор не может воспроизвести этот файл. Выберите другое фото или видео, снятое на iPhone.",
                              "Der Fernseher kann diese Datei nicht abspielen. Versuche ein anderes Foto oder ein mit dem iPhone aufgenommenes Video.",
                              "Le téléviseur ne peut pas lire ce fichier. Essayez une autre photo ou une vidéo filmée avec l’iPhone."),
    "error.med-003.title": ("Couldn’t load the file", "No se pudo cargar el archivo", "Не удалось загрузить файл", "Datei konnte nicht geladen werden", "Impossible de charger le fichier"),
    "error.med-003.message": ("The selected item couldn’t be read. It may have been deleted or access was removed. Choose it again.",
                              "No se pudo leer el elemento. Puede que se haya eliminado o se haya retirado el acceso. Vuelve a elegirlo.",
                              "Не удалось прочитать выбранный файл. Возможно, он удалён или доступ отозван. Выберите его снова.",
                              "Das gewählte Objekt konnte nicht gelesen werden. Es wurde eventuell gelöscht oder der Zugriff entzogen. Wähle es erneut.",
                              "L’élément choisi n’a pas pu être lu. Il a peut-être été supprimé ou l’accès retiré. Choisissez-le à nouveau."),
    "error.med-004.title": ("iCloud download failed", "Error al descargar de iCloud", "Не удалось загрузить из iCloud", "Download aus iCloud fehlgeschlagen", "Échec du téléchargement depuis iCloud"),
    "error.med-004.message": ("The original is stored in iCloud and couldn’t be downloaded. Check your internet connection and try again.",
                              "El original está en iCloud y no se pudo descargar. Comprueba tu conexión a internet e inténtalo de nuevo.",
                              "Оригинал хранится в iCloud и не загрузился. Проверьте подключение к интернету и повторите попытку.",
                              "Das Original liegt in iCloud und konnte nicht geladen werden. Prüfe deine Internetverbindung und versuche es erneut.",
                              "L’original est dans iCloud et n’a pas pu être téléchargé. Vérifiez votre connexion Internet et réessayez."),
    "error.med-005.title": ("Not enough storage", "Espacio insuficiente", "Недостаточно места", "Nicht genug Speicher", "Stockage insuffisant"),
    "error.med-005.message": ("Preparing this video needs free space on your iPhone. Free up some space or choose a shorter video.",
                              "Preparar este vídeo requiere espacio libre en el iPhone. Libera espacio o elige un vídeo más corto.",
                              "Для подготовки видео нужно свободное место на iPhone. Освободите место или выберите видео короче.",
                              "Zum Vorbereiten des Videos wird freier Speicher benötigt. Schaffe Platz oder wähle ein kürzeres Video.",
                              "La préparation de cette vidéo nécessite de l’espace libre. Libérez de l’espace ou choisissez une vidéo plus courte."),
    "error.med-006.title": ("Playback didn’t start", "La reproducción no empezó", "Воспроизведение не началось", "Wiedergabe hat nicht gestartet", "La lecture n’a pas démarré"),
    "error.med-006.message": ("The TV didn’t start playing. Try again, or check that nothing else is using the TV’s media player.",
                              "La TV no empezó a reproducir. Inténtalo de nuevo o comprueba que nada más esté usando su reproductor.",
                              "Телевизор не начал воспроизведение. Попробуйте снова или проверьте, не занят ли его плеер.",
                              "Der Fernseher hat nicht mit der Wiedergabe begonnen. Versuche es erneut oder prüfe, ob der Player belegt ist.",
                              "Le téléviseur n’a pas lancé la lecture. Réessayez ou vérifiez que son lecteur n’est pas déjà utilisé."),
    "error.mir-001.title": ("Mirroring receiver not available", "Receptor de duplicación no disponible", "Приёмник трансляции недоступен", "Spiegelungsempfänger nicht verfügbar", "Récepteur de recopie indisponible"),
    "error.mir-001.message": ("Our Screen Mirroring needs the TV’s web browser, which this TV doesn’t offer or didn’t open. Photos and videos may still work on this TV.",
                              "Nuestra duplicación de pantalla necesita el navegador de la TV, que esta TV no ofrece o no abrió. Puede que las fotos y los vídeos sí funcionen en esta TV.",
                              "Для нашей трансляции нужен браузер телевизора, а на этом телевизоре его нет или он не открылся. Фото и видео на этом телевизоре могут работать.",
                              "Unsere Spiegelung braucht den Webbrowser des Fernsehers, den dieses Gerät nicht bietet oder nicht geöffnet hat. Fotos und Videos funktionieren eventuell trotzdem.",
                              "Notre recopie nécessite le navigateur du téléviseur, absent ou non ouvert ici. Les photos et vidéos peuvent tout de même fonctionner sur ce téléviseur."),
    "error.mir-002.title": ("TV browser didn’t open", "No se abrió el navegador de la TV", "Браузер телевизора не открылся", "TV-Browser hat sich nicht geöffnet", "Le navigateur du téléviseur ne s’est pas ouvert"),
    "error.mir-002.message": ("Open the TV’s web browser once manually, then try again.",
                              "Abre una vez el navegador de la TV manualmente y vuelve a intentarlo.",
                              "Откройте браузер на телевизоре вручную один раз и попробуйте снова.",
                              "Öffne den Webbrowser des Fernsehers einmal manuell und versuche es erneut.",
                              "Ouvrez une fois le navigateur du téléviseur manuellement, puis réessayez."),
    "error.mir-003.title": ("Mirroring stopped by iOS", "iOS detuvo la duplicación", "iOS остановила трансляцию", "iOS hat die Spiegelung beendet", "iOS a arrêté la recopie"),
    "error.mir-003.message": ("The screen recording was ended by the system. Start mirroring again when you’re ready.",
                              "El sistema finalizó la grabación de pantalla. Vuelve a iniciar la duplicación cuando quieras.",
                              "Система завершила запись экрана. Начните трансляцию снова, когда будете готовы.",
                              "Das System hat die Bildschirmaufnahme beendet. Starte die Spiegelung erneut, wenn du bereit bist.",
                              "Le système a arrêté l’enregistrement de l’écran. Relancez la recopie quand vous êtes prêt."),
    "error.mir-004.title": ("Network connection lost", "Se perdió la conexión de red", "Сетевое соединение потеряно", "Netzwerkverbindung unterbrochen", "Connexion réseau perdue"),
    "error.mir-004.message": ("Mirroring stopped because the TV or Wi‑Fi disconnected. Check the network and start again.",
                              "La duplicación se detuvo porque la TV o el Wi‑Fi se desconectó. Revisa la red y vuelve a empezar.",
                              "Трансляция остановлена: отключился телевизор или Wi‑Fi. Проверьте сеть и начните снова.",
                              "Die Spiegelung wurde beendet, weil Fernseher oder WLAN getrennt wurden. Prüfe das Netzwerk und starte neu.",
                              "La recopie s’est arrêtée car le téléviseur ou le Wi‑Fi s’est déconnecté. Vérifiez le réseau et recommencez."),
    "error.mir-005.title": ("Protected content", "Contenido protegido", "Защищённый контент", "Geschützte Inhalte", "Contenu protégé"),
    "error.mir-005.message": ("Streaming apps often block screen capture, so the TV may show a black picture. Open the service directly on the TV instead.",
                              "Las apps de streaming suelen bloquear la captura de pantalla y la TV puede verse en negro. Abre el servicio directamente en la TV.",
                              "Стриминговые сервисы часто запрещают захват экрана, поэтому на телевизоре может быть чёрный экран. Откройте сервис прямо на телевизоре.",
                              "Streaming-Apps blockieren oft die Bildschirmaufnahme, daher kann das Bild schwarz sein. Öffne den Dienst direkt am Fernseher.",
                              "Les apps de streaming bloquent souvent la capture d’écran : l’image peut être noire. Ouvrez plutôt le service sur le téléviseur."),
    "error.mir-006.title": ("iPhone is too warm", "El iPhone está demasiado caliente", "iPhone слишком нагрелся", "iPhone ist zu warm", "L’iPhone est trop chaud"),
    "error.mir-006.message": ("Mirroring stopped to protect your iPhone. Let it cool down, then start again.",
                              "La duplicación se detuvo para proteger el iPhone. Deja que se enfríe y vuelve a empezar.",
                              "Трансляция остановлена, чтобы защитить iPhone. Дайте ему остыть и начните снова.",
                              "Die Spiegelung wurde zum Schutz deines iPhone beendet. Lass es abkühlen und starte neu.",
                              "La recopie s’est arrêtée pour protéger votre iPhone. Laissez-le refroidir, puis recommencez."),
    "error.mir-007.title": ("Mirroring didn’t start", "La duplicación no se inició", "Трансляция не началась", "Spiegelung hat nicht gestartet", "La recopie n’a pas démarré"),
    "error.mir-007.message": ("We couldn’t set up the connection on this network. Check Wi‑Fi and try again.",
                              "No pudimos establecer la conexión en esta red. Comprueba el Wi‑Fi e inténtalo de nuevo.",
                              "Не удалось установить соединение в этой сети. Проверьте Wi‑Fi и попробуйте снова.",
                              "Die Verbindung konnte in diesem Netzwerk nicht aufgebaut werden. Prüfe das WLAN und versuche es erneut.",
                              "Impossible d’établir la connexion sur ce réseau. Vérifiez le Wi‑Fi et réessayez."),
    "error.iap-001.title": ("Plans couldn’t be loaded", "No se pudieron cargar los planes", "Не удалось загрузить тарифы", "Tarife konnten nicht geladen werden", "Impossible de charger les offres"),
    "error.iap-001.message": ("The App Store didn’t respond. Check your internet connection and try again.",
                              "El App Store no respondió. Comprueba tu conexión a internet e inténtalo de nuevo.",
                              "App Store не ответил. Проверьте подключение к интернету и попробуйте снова.",
                              "Der App Store hat nicht geantwortet. Prüfe deine Internetverbindung und versuche es erneut.",
                              "L’App Store n’a pas répondu. Vérifiez votre connexion Internet et réessayez."),
    "error.iap-002.title": ("Purchase awaiting approval", "Compra pendiente de aprobación", "Покупка ожидает подтверждения", "Kauf wartet auf Genehmigung", "Achat en attente d’approbation"),
    "error.iap-002.message": ("The App Store is waiting for approval (for example Ask to Buy). Access starts automatically once it’s approved.",
                              "El App Store espera una aprobación (por ejemplo, «Solicitar la compra»). El acceso empezará automáticamente al aprobarse.",
                              "App Store ждёт подтверждения (например, «Попросить купить»). Доступ откроется автоматически после одобрения.",
                              "Der App Store wartet auf eine Genehmigung (z. B. „Kaufanfrage“). Der Zugriff startet automatisch nach der Freigabe.",
                              "L’App Store attend une approbation (par exemple « Autorisation d’achat »). L’accès démarrera automatiquement une fois approuvé."),
    "error.iap-003.title": ("Purchase not completed", "Compra no completada", "Покупка не завершена", "Kauf nicht abgeschlossen", "Achat non finalisé"),
    "error.iap-003.message": ("You weren’t charged by us. Try again, or check your payment method in your Apple Account.",
                              "No hemos realizado ningún cargo. Inténtalo de nuevo o revisa el método de pago de tu cuenta de Apple.",
                              "Мы ничего не списали. Попробуйте снова или проверьте способ оплаты в Apple Account.",
                              "Wir haben nichts abgebucht. Versuche es erneut oder prüfe die Zahlungsmethode deines Apple Accounts.",
                              "Aucun paiement n’a été effectué. Réessayez ou vérifiez le moyen de paiement de votre compte Apple."),
    "error.iap-004.title": ("Purchases are restricted", "Compras restringidas", "Покупки ограничены", "Käufe sind eingeschränkt", "Achats restreints"),
    "error.iap-004.message": ("In‑app purchases are turned off on this device (for example by Screen Time).",
                              "Las compras dentro de apps están desactivadas en este dispositivo (por ejemplo, por Tiempo de uso).",
                              "Встроенные покупки отключены на этом устройстве (например, в «Экранном времени»).",
                              "In‑App-Käufe sind auf diesem Gerät deaktiviert (z. B. durch Bildschirmzeit).",
                              "Les achats intégrés sont désactivés sur cet appareil (par exemple via Temps d’écran)."),
    "error.iap-005.title": ("No purchases found", "No se encontraron compras", "Покупки не найдены", "Keine Käufe gefunden", "Aucun achat trouvé"),
    "error.iap-005.message": ("No Remote Pro purchase is linked to the Apple Account on this device. Check which account you used to buy.",
                              "No hay ninguna compra de Remote Pro vinculada a la cuenta de Apple de este dispositivo. Comprueba con qué cuenta compraste.",
                              "С Apple Account на этом устройстве не связано ни одной покупки Remote Pro. Проверьте, с какого аккаунта была покупка.",
                              "Mit dem Apple Account auf diesem Gerät ist kein Remote Pro-Kauf verknüpft. Prüfe, mit welchem Account du gekauft hast.",
                              "Aucun achat Remote Pro n’est associé au compte Apple de cet appareil. Vérifiez le compte utilisé pour l’achat."),
    "error.iap-006.title": ("Couldn’t check your access", "No se pudo comprobar tu acceso", "Не удалось проверить доступ", "Zugriff konnte nicht geprüft werden", "Impossible de vérifier votre accès"),
    "error.iap-006.message": ("We’ll keep using your last verified access and check again automatically.",
                              "Seguiremos usando tu último acceso verificado y volveremos a comprobarlo automáticamente.",
                              "Мы продолжим использовать последний подтверждённый доступ и проверим его снова автоматически.",
                              "Wir nutzen weiter deinen zuletzt bestätigten Zugriff und prüfen automatisch erneut.",
                              "Nous continuons d’utiliser votre dernier accès vérifié et revérifierons automatiquement."),
    "error.ofr-001.title": ("Offer not available", "Oferta no disponible", "Предложение недоступно", "Angebot nicht verfügbar", "Offre indisponible"),
    "error.ofr-001.message": ("This offer isn’t available for your account or region right now. Standard plans are still available.",
                              "Esta oferta no está disponible ahora para tu cuenta o región. Los planes estándar siguen disponibles.",
                              "Это предложение сейчас недоступно для вашего аккаунта или региона. Обычные тарифы по-прежнему доступны.",
                              "Dieses Angebot ist für deinen Account oder deine Region gerade nicht verfügbar. Die Standardtarife bleiben verfügbar.",
                              "Cette offre n’est pas disponible pour votre compte ou région. Les offres standard restent disponibles."),
    "error.ofr-002.title": ("Offer expired", "La oferta caducó", "Срок предложения истёк", "Angebot abgelaufen", "Offre expirée"),
    "error.ofr-002.message": ("The activation period for this bonus has ended.",
                              "El plazo para activar este bono terminó.",
                              "Срок активации этого бонуса закончился.",
                              "Der Aktivierungszeitraum für diesen Bonus ist abgelaufen.",
                              "La période d’activation de ce bonus est terminée."),
    "error.ofr-003.title": ("Offer already used", "Oferta ya utilizada", "Предложение уже использовано", "Angebot bereits genutzt", "Offre déjà utilisée"),
    "error.ofr-003.message": ("This bonus code was already redeemed.",
                              "Este código de bono ya se canjeó.",
                              "Этот бонусный код уже активирован.",
                              "Dieser Bonuscode wurde bereits eingelöst.",
                              "Ce code bonus a déjà été utilisé."),
    "error.ofr-004.title": ("Bonuses are gone for now", "Los bonos se agotaron por ahora", "Бонусы пока закончились", "Boni sind vorerst vergeben", "Les bonus sont épuisés pour le moment"),
    "error.ofr-004.message": ("All bonus codes of this campaign have been handed out.",
                              "Se entregaron todos los códigos de esta campaña.",
                              "Все бонусные коды этой акции уже выданы.",
                              "Alle Bonuscodes dieser Aktion wurden vergeben.",
                              "Tous les codes de cette campagne ont été distribués."),
    "error.ofr-005.title": ("Bonus service unavailable", "Servicio de bonos no disponible", "Сервис бонусов недоступен", "Bonusdienst nicht verfügbar", "Service de bonus indisponible"),
    "error.ofr-005.message": ("Your result is saved. Try activating again later — nothing was charged.",
                              "Tu resultado está guardado. Intenta activarlo más tarde; no se ha cobrado nada.",
                              "Ваш результат сохранён. Попробуйте активировать позже — ничего не списано.",
                              "Dein Ergebnis ist gespeichert. Versuche die Aktivierung später erneut – es wurde nichts berechnet.",
                              "Votre résultat est enregistré. Réessayez plus tard : rien n’a été facturé."),
    "error.sup-001.title": ("Mail isn’t set up", "Mail no está configurado", "Почта не настроена", "Mail ist nicht eingerichtet", "Mail n’est pas configuré"),
    "error.sup-001.message": ("Copy the address and text, or use the web form instead.",
                              "Copia la dirección y el texto, o usa el formulario web.",
                              "Скопируйте адрес и текст или воспользуйтесь веб-формой.",
                              "Kopiere Adresse und Text oder nutze das Webformular.",
                              "Copiez l’adresse et le texte, ou utilisez le formulaire web."),
    "error.sup-002.title": ("Support contact not configured", "Contacto de soporte no configurado", "Контакты поддержки не настроены", "Support-Kontakt nicht eingerichtet", "Contact d’assistance non configuré"),
    "error.sup-002.message": ("You can still copy your message and read the Help Center.",
                              "Aun así puedes copiar tu mensaje y leer el Centro de ayuda.",
                              "Вы можете скопировать сообщение и прочитать справку.",
                              "Du kannst deine Nachricht trotzdem kopieren und die Hilfe lesen.",
                              "Vous pouvez toujours copier votre message et consulter l’aide."),
    "error.gen-001.title": ("Something went wrong", "Algo salió mal", "Что-то пошло не так", "Etwas ist schiefgelaufen", "Un problème est survenu"),
    "error.gen-001.message": ("Please try again. If it keeps happening, contact support.",
                              "Inténtalo de nuevo. Si sigue ocurriendo, contacta con soporte.",
                              "Попробуйте снова. Если ошибка повторяется, напишите в поддержку.",
                              "Bitte versuche es erneut. Wenn es weiter passiert, kontaktiere den Support.",
                              "Veuillez réessayer. Si le problème persiste, contactez l’assistance."),

    # --- Recovery actions -----------------------------------------------------------------
    "action.retry": ("Try again", "Reintentar", "Повторить", "Erneut versuchen", "Réessayer"),
    "action.openSettings": ("Open Settings", "Abrir Ajustes", "Открыть Настройки", "Einstellungen öffnen", "Ouvrir Réglages"),
    "action.pairAgain": ("Pair again", "Vincular de nuevo", "Подключить заново", "Erneut koppeln", "Associer à nouveau"),
    "action.searchAgain": ("Search again", "Buscar de nuevo", "Искать снова", "Erneut suchen", "Relancer la recherche"),
    "action.useButtons": ("Use buttons", "Usar botones", "Использовать кнопки", "Tasten verwenden", "Utiliser les touches"),
    "action.openHome": ("Go to Home", "Ir a Inicio", "На главный экран", "Zum Startbildschirm", "Aller à l’accueil"),
    "action.chooseAnotherFile": ("Choose another file", "Elegir otro archivo", "Выбрать другой файл", "Andere Datei wählen", "Choisir un autre fichier"),
    "action.showSetupSteps": ("Show setup steps", "Ver pasos de configuración", "Показать шаги настройки", "Einrichtungsschritte anzeigen", "Voir les étapes"),
    "action.restorePurchases": ("Restore Purchases", "Restaurar compras", "Восстановить покупки", "Käufe wiederherstellen", "Restaurer les achats"),
    "action.managePayment": ("Manage payment", "Gestionar pago", "Управление оплатой", "Zahlung verwalten", "Gérer le paiement"),
    "action.contactSupport": ("Contact support", "Contactar con soporte", "Написать в поддержку", "Support kontaktieren", "Contacter l’assistance"),
    "action.turnOnWithRemote": ("Turn on with the TV remote", "Encender con el mando de la TV", "Включить пультом телевизора", "Mit der TV-Fernbedienung einschalten", "Allumer avec la télécommande"),

    # --- Capabilities -------------------------------------------------------------------
    "capability.remoteControl": ("Remote buttons", "Botones del mando", "Кнопки пульта", "Fernbedienungstasten", "Touches de télécommande"),
    "capability.textInput": ("Typing from iPhone", "Escribir desde el iPhone", "Ввод текста с iPhone", "Tippen vom iPhone", "Saisie depuis l’iPhone"),
    "capability.appLaunch": ("Opening TV apps", "Abrir apps de la TV", "Запуск приложений ТВ", "TV-Apps öffnen", "Ouverture des apps TV"),
    "capability.photos": ("Photos on TV", "Fotos en la TV", "Фото на ТВ", "Fotos auf dem Fernseher", "Photos sur le téléviseur"),
    "capability.video": ("Videos on TV", "Vídeos en la TV", "Видео на ТВ", "Videos auf dem Fernseher", "Vidéos sur le téléviseur"),
    "capability.screenMirroring": ("Screen Mirroring", "Duplicar pantalla", "Трансляция экрана", "Bildschirm spiegeln", "Recopie de l’écran"),
    "capability.powerOff": ("Turning off", "Apagar", "Выключение", "Ausschalten", "Extinction"),
    "capability.wakeOnNetwork": ("Turning on over Wi‑Fi", "Encender por Wi‑Fi", "Включение по Wi‑Fi", "Einschalten über WLAN", "Allumage via Wi‑Fi"),
    "capability.status.unknown": ("Not checked", "Sin comprobar", "Не проверено", "Nicht geprüft", "Non vérifié"),
    "capability.status.supported": ("Works", "Funciona", "Работает", "Funktioniert", "Fonctionne"),
    "capability.status.limited": ("Works with limits", "Funciona con límites", "Работает с ограничениями", "Mit Einschränkungen", "Avec limites"),
    "capability.status.unsupported": ("Not available", "No disponible", "Недоступно", "Nicht verfügbar", "Indisponible"),
    "capability.status.checking": ("Checking…", "Comprobando…", "Проверяем…", "Wird geprüft …", "Vérification…"),
    "capability.note.holdNotSupported": ("Holding a key repeats it instead of a long press.", "Mantener pulsada una tecla la repite en lugar de una pulsación larga.", "Удержание кнопки повторяет нажатие, а не делает долгое нажатие.", "Gedrückthalten wiederholt die Taste statt eines langen Drucks.", "Maintenir une touche la répète au lieu d’un appui long."),
    "capability.note.textNeedsFocusedField": ("Works when a text field is selected on the TV; not every TV app accepts it.", "Funciona cuando hay un campo de texto seleccionado en la TV; no todas las apps lo aceptan.", "Работает, когда на телевизоре выбрано поле ввода; не все приложения ТВ это поддерживают.", "Funktioniert, wenn am Fernseher ein Textfeld ausgewählt ist; nicht jede TV-App unterstützt das.", "Fonctionne quand un champ de texte est sélectionné ; toutes les apps TV ne l’acceptent pas."),
    "capability.note.textReplaceOnly": ("Text is sent as a whole; editing happens on the phone.", "El texto se envía completo; la edición se hace en el teléfono.", "Текст отправляется целиком; правка — на телефоне.", "Text wird als Ganzes gesendet; bearbeitet wird am Telefon.", "Le texte est envoyé en entier ; la modification se fait sur le téléphone."),
    "capability.note.appListIsCatalog": ("The TV doesn’t report installed apps, so a catalog of common services is shown.", "La TV no informa de sus apps instaladas; se muestra un catálogo de servicios habituales.", "Телевизор не сообщает установленные приложения — показан каталог популярных сервисов.", "Der Fernseher meldet keine installierten Apps, daher wird ein Katalog bekannter Dienste gezeigt.", "Le téléviseur n’indique pas ses apps installées : un catalogue de services courants est affiché."),
    "capability.note.appLaunchUnconfirmed": ("The TV may not confirm that an app opened.", "Es posible que la TV no confirme que la app se abrió.", "Телевизор может не подтверждать открытие приложения.", "Der Fernseher bestätigt das Öffnen einer App eventuell nicht.", "Le téléviseur peut ne pas confirmer l’ouverture d’une app."),
    "capability.note.noMediaRenderer": ("No media receiver (DLNA) found on this TV.", "No se encontró un receptor multimedia (DLNA) en esta TV.", "На телевизоре не найден медиаприёмник (DLNA).", "Kein Medienempfänger (DLNA) auf diesem Fernseher gefunden.", "Aucun récepteur multimédia (DLNA) trouvé sur ce téléviseur."),
    "capability.note.mediaRendererUnreachable": ("The media receiver didn’t respond.", "El receptor multimedia no respondió.", "Медиаприёмник не ответил.", "Der Medienempfänger hat nicht geantwortet.", "Le récepteur multimédia n’a pas répondu."),
    "capability.note.videoFormatLimited": ("Some formats need conversion first; not every format plays.", "Algunos formatos necesitan conversión; no todos se reproducen.", "Некоторые форматы нужно конвертировать; воспроизводятся не все.", "Manche Formate müssen erst konvertiert werden; nicht jedes Format läuft.", "Certains formats doivent être convertis ; tous ne sont pas lus."),
    "capability.note.mirroringNeedsBrowser": ("Uses the TV’s web browser as receiver; latency is higher than a cable.", "Usa el navegador de la TV como receptor; la latencia es mayor que con cable.", "Приёмник — браузер телевизора; задержка выше, чем по кабелю.", "Nutzt den Webbrowser des Fernsehers als Empfänger; die Verzögerung ist höher als per Kabel.", "Utilise le navigateur du téléviseur comme récepteur ; la latence est supérieure à un câble."),
    "capability.note.mirroringNoBrowserOnPlatform": ("This TV has no web browser we can use, so our Screen Mirroring isn’t available.", "Esta TV no tiene un navegador que podamos usar, así que nuestra duplicación no está disponible.", "На этом телевизоре нет подходящего браузера, поэтому наша трансляция экрана недоступна.", "Dieser Fernseher hat keinen nutzbaren Webbrowser, daher ist unsere Spiegelung nicht verfügbar.", "Ce téléviseur n’a pas de navigateur utilisable : notre recopie n’est pas disponible."),
    "capability.note.mirroringVideoOnlyNoAudio": ("Picture only — sound stays on the iPhone.", "Solo imagen: el sonido sigue en el iPhone.", "Только изображение — звук остаётся на iPhone.", "Nur Bild – der Ton bleibt auf dem iPhone.", "Image uniquement : le son reste sur l’iPhone."),
    "capability.note.airPlayAvailable": ("This TV advertises AirPlay: iPhone’s own Screen Mirroring from Control Center may work, free.", "Esta TV anuncia AirPlay: la duplicación propia del iPhone desde el Centro de control puede funcionar, gratis.", "Телевизор поддерживает AirPlay: может работать встроенный «Повтор экрана» iPhone из Пункта управления — бесплатно.", "Dieser Fernseher meldet AirPlay: Die eigene Bildschirmsynchronisierung des iPhone im Kontrollzentrum kann kostenlos funktionieren.", "Ce téléviseur annonce AirPlay : la Recopie de l’écran intégrée à l’iPhone peut fonctionner gratuitement."),
    "capability.note.wakeNeedsMulticastEntitlement": ("Turning on over Wi‑Fi needs a network permission from Apple that this version may not have.", "Encender por Wi‑Fi requiere un permiso de red de Apple que esta versión puede no tener.", "Для включения по Wi‑Fi нужно сетевое разрешение Apple, которого в этой версии может не быть.", "Einschalten über WLAN braucht eine Netzwerkberechtigung von Apple, die diese Version eventuell nicht hat.", "L’allumage via Wi‑Fi nécessite une autorisation réseau d’Apple dont cette version peut ne pas disposer."),
    "capability.note.wakeNeedsMacAddress": ("The TV didn’t share the information needed to turn it on remotely.", "La TV no compartió la información necesaria para encenderla a distancia.", "Телевизор не сообщил данные, нужные для удалённого включения.", "Der Fernseher hat die Daten zum Einschalten aus der Ferne nicht geteilt.", "Le téléviseur n’a pas partagé les informations nécessaires pour l’allumer à distance."),
    "capability.note.wakeNeedsTVSetting": ("The TV must allow being turned on by mobile/network in its settings.", "La TV debe permitir encenderse desde el móvil o la red en sus ajustes.", "В настройках телевизора должно быть разрешено включение по сети или с телефона.", "Der Fernseher muss in den Einstellungen das Einschalten per Mobilgerät/Netzwerk erlauben.", "Le téléviseur doit autoriser l’allumage par mobile ou réseau dans ses réglages."),
    "capability.note.notCheckedYet": ("Not checked yet.", "Aún sin comprobar.", "Ещё не проверено.", "Noch nicht geprüft.", "Pas encore vérifié."),
    "capability.note.protocolUnsupported": ("This TV’s protocol doesn’t offer it.", "El protocolo de esta TV no lo ofrece.", "Протокол этого телевизора не поддерживает эту функцию.", "Das Protokoll dieses Fernsehers bietet das nicht.", "Le protocole de ce téléviseur ne le propose pas."),

    # --- Remote key names (VoiceOver) ---------------------------------------------------
    "key.up": ("Up", "Arriba", "Вверх", "Nach oben", "Haut"),
    "key.down": ("Down", "Abajo", "Вниз", "Nach unten", "Bas"),
    "key.left": ("Left", "Izquierda", "Влево", "Links", "Gauche"),
    "key.right": ("Right", "Derecha", "Вправо", "Rechts", "Droite"),
    "key.ok": ("OK, select", "OK, seleccionar", "OK, выбрать", "OK, auswählen", "OK, sélectionner"),
    "key.ok.short": ("OK", "OK", "OK", "OK", "OK"),
    "key.back": ("Back", "Atrás", "Назад", "Zurück", "Retour"),
    "key.home": ("Home", "Inicio", "Домой", "Home", "Accueil"),
    "key.menu": ("Menu", "Menú", "Меню", "Menü", "Menu"),
    "key.settings": ("TV settings", "Ajustes de la TV", "Настройки ТВ", "TV-Einstellungen", "Réglages du téléviseur"),
    "key.info": ("Info", "Información", "Информация", "Info", "Infos"),
    "key.guide": ("Guide", "Guía", "Телегид", "Programmführer", "Guide"),
    "key.input": ("Input source", "Fuente de entrada", "Источник сигнала", "Eingangsquelle", "Source d’entrée"),
    "key.volumeUp": ("Volume up", "Subir volumen", "Громче", "Lauter", "Volume +"),
    "key.volumeDown": ("Volume down", "Bajar volumen", "Тише", "Leiser", "Volume −"),
    "key.mute": ("Mute", "Silenciar", "Без звука", "Stumm", "Muet"),
    "key.channelUp": ("Next channel", "Canal siguiente", "Следующий канал", "Nächster Sender", "Chaîne suivante"),
    "key.channelDown": ("Previous channel", "Canal anterior", "Предыдущий канал", "Vorheriger Sender", "Chaîne précédente"),
    "key.playPause": ("Play or pause", "Reproducir o pausar", "Воспроизведение или пауза", "Wiedergabe oder Pause", "Lecture ou pause"),
    "key.play": ("Play", "Reproducir", "Воспроизвести", "Wiedergabe", "Lecture"),
    "key.pause": ("Pause", "Pausa", "Пауза", "Pause", "Pause"),
    "key.stop": ("Stop", "Detener", "Стоп", "Stopp", "Arrêt"),
    "key.rewind": ("Rewind", "Retroceder", "Перемотка назад", "Zurückspulen", "Retour rapide"),
    "key.fastForward": ("Fast forward", "Avanzar", "Перемотка вперёд", "Vorspulen", "Avance rapide"),
    "key.next": ("Next", "Siguiente", "Далее", "Weiter", "Suivant"),
    "key.previous": ("Previous", "Anterior", "Назад к предыдущему", "Zurück", "Précédent"),
    "key.powerOff": ("Turn TV off", "Apagar la TV", "Выключить телевизор", "Fernseher ausschalten", "Éteindre le téléviseur"),
    "key.powerToggle": ("Power", "Encendido", "Питание", "Ein/Aus", "Marche/Arrêt"),
    "key.digit0": ("0", "0", "0", "0", "0"),
    "key.digit1": ("1", "1", "1", "1", "1"),
    "key.digit2": ("2", "2", "2", "2", "2"),
    "key.digit3": ("3", "3", "3", "3", "3"),
    "key.digit4": ("4", "4", "4", "4", "4"),
    "key.digit5": ("5", "5", "5", "5", "5"),
    "key.digit6": ("6", "6", "6", "6", "6"),
    "key.digit7": ("7", "7", "7", "7", "7"),
    "key.digit8": ("8", "8", "8", "8", "8"),
    "key.digit9": ("9", "9", "9", "9", "9"),
}

PLURALS = {}
