# Localization source: paywall, plans, Remote Pro management, plan changes, bonus.
# Tuple order: (en, es, ru, de, fr).
# NOTE: payment and legal wording requires review by a native editor before release.

STRINGS = {
    # Plans & prices
    "plan.monthly": ("Monthly", "Mensual", "Месяц", "Monatlich", "Mensuel"),
    "plan.yearly": ("Yearly", "Anual", "Год", "Jährlich", "Annuel"),
    "plan.lifetime": ("Lifetime Access", "Acceso de por vida", "Доступ навсегда", "Dauerhafter Zugriff", "Accès à vie"),
    "price.perMonth": ("%@ / month", "%@ / mes", "%@ / месяц", "%@ / Monat", "%@ / mois"),
    "price.perYear": ("%@ / year", "%@ / año", "%@ / год", "%@ / Jahr", "%@ / an"),
    "price.perMonth.sentence": ("%@ per month", "%@ al mes", "%@ в месяц", "%@ pro Monat", "%@ par mois"),
    "price.perYear.sentence": ("%@ per year", "%@ al año", "%@ в год", "%@ pro Jahr", "%@ par an"),

    # Paywall
    "paywall.remote.title": ("Your TV.\nOne remote.", "Tu TV.\nUn solo mando.", "Ваш телевизор.\nОдин пульт.", "Dein Fernseher.\nEine Fernbedienung.", "Votre téléviseur.\nUne télécommande."),
    "paywall.remote.subtitle": ("Control your TV, type from your iPhone, and open your favorite apps.", "Controla tu TV, escribe desde el iPhone y abre tus apps favoritas.", "Управляйте телевизором, вводите текст с iPhone и открывайте любимые приложения.", "Steuere deinen Fernseher, tippe vom iPhone und öffne deine Lieblings-Apps.", "Contrôlez votre téléviseur, tapez depuis l’iPhone et ouvrez vos apps préférées."),
    "paywall.mirroring.title": ("Bring your screen\nto the big screen.", "Lleva tu pantalla\na la pantalla grande.", "Ваш экран —\nна большом экране.", "Dein Bildschirm auf\ndem großen Bildschirm.", "Votre écran\nsur grand écran."),
    "paywall.mirroring.subtitle": ("Share photos, videos, and your screen with a compatible TV.", "Comparte fotos, vídeos y tu pantalla con una TV compatible.", "Показывайте фото, видео и экран на совместимом телевизоре.", "Teile Fotos, Videos und deinen Bildschirm mit einem kompatiblen Fernseher.", "Partagez photos, vidéos et votre écran avec un téléviseur compatible."),
    "paywall.reason.remote": ("You’ve used the free remote check on this TV.", "Has usado la comprobación gratuita del mando en esta TV.", "Вы использовали бесплатную проверку пульта на этом ТВ.", "Du hast den kostenlosen Fernbedienungstest auf diesem Fernseher genutzt.", "Vous avez utilisé la vérification gratuite de la télécommande sur ce téléviseur."),
    "paywall.reason.photo": ("You’ve used the free test photo on this TV.", "Has usado la foto de prueba gratuita en esta TV.", "Вы использовали бесплатное тестовое фото на этом ТВ.", "Du hast das kostenlose Testfoto auf diesem Fernseher genutzt.", "Vous avez utilisé la photo test gratuite sur ce téléviseur."),
    "paywall.reason.mirroring": ("You’ve used the free mirroring test on this TV.", "Has usado la prueba gratuita de duplicación en esta TV.", "Вы использовали бесплатную проверку трансляции на этом ТВ.", "Du hast den kostenlosen Spiegelungstest auf diesem Fernseher genutzt.", "Vous avez utilisé le test gratuit de recopie sur ce téléviseur."),
    "paywall.compat.checked": ("Checked on “%@”: the remote works with this TV.", "Comprobado en «%@»: el mando funciona con esta TV.", "Проверено на «%@»: пульт работает с этим ТВ.", "Geprüft mit „%@“: Die Fernbedienung funktioniert mit diesem Fernseher.", "Vérifié sur « %@ » : la télécommande fonctionne avec ce téléviseur."),
    "paywall.compat.noMirroring": ("“%@” doesn’t support our Screen Mirroring, and Remote Pro won’t change that. Remote control and other supported features work.", "«%@» no admite nuestra duplicación y Remote Pro no lo cambia. El mando y otras funciones compatibles sí funcionan.", "«%@» не поддерживает нашу трансляцию экрана, и Remote Pro этого не изменит. Пульт и другие поддерживаемые функции работают.", "„%@“ unterstützt unsere Spiegelung nicht, daran ändert Remote Pro nichts. Fernbedienung und andere unterstützte Funktionen funktionieren.", "« %@ » ne prend pas en charge notre recopie, et Remote Pro n’y change rien. La télécommande et les autres fonctions prises en charge marchent."),
    "paywall.benefit.remote": ("Unlimited remote control", "Control remoto ilimitado", "Пульт без ограничений", "Unbegrenzte Fernbedienung", "Télécommande illimitée"),
    "paywall.benefit.keyboardApps": ("Keyboard and app shortcuts", "Teclado y accesos a apps", "Клавиатура и быстрый запуск приложений", "Tastatur und App-Verknüpfungen", "Clavier et raccourcis d’apps"),
    "paywall.benefit.mirroringNoLimit": ("Screen Mirroring without an app-imposed time limit", "Duplicar pantalla sin límite de tiempo impuesto por la app", "Трансляция экрана без ограничения времени со стороны приложения", "Bildschirmspiegelung ohne Zeitlimit durch die App", "Recopie de l’écran sans limite de temps imposée par l’app"),
    "paywall.benefit.photosVideos": ("Photo and video sharing", "Compartir fotos y vídeos", "Показ фото и видео", "Fotos und Videos teilen", "Partage de photos et vidéos"),
    "paywall.benefit.remoteIncluded": ("Full remote control included", "Control remoto completo incluido", "Полный пульт в комплекте", "Volle Fernbedienung inklusive", "Télécommande complète incluse"),
    "paywall.samePlans": ("Monthly, yearly and lifetime unlock exactly the same features on all your supported TVs.", "Mensual, anual y de por vida desbloquean las mismas funciones en todas tus TV compatibles.", "Месяц, год и доступ навсегда открывают одинаковые функции на всех ваших совместимых ТВ.", "Monatlich, jährlich und dauerhaft schalten genau dieselben Funktionen für alle unterstützten Fernseher frei.", "Mensuel, annuel et à vie débloquent exactement les mêmes fonctions sur tous vos téléviseurs pris en charge."),
    "paywall.loading": ("Loading plans…", "Cargando planes…", "Загружаем тарифы…", "Tarife werden geladen …", "Chargement des offres…"),
    "paywall.someUnavailable": ("Some plans aren’t available in your App Store region right now.", "Algunos planes no están disponibles ahora en tu región del App Store.", "Некоторые тарифы сейчас недоступны в вашем регионе App Store.", "Einige Tarife sind in deiner App Store-Region gerade nicht verfügbar.", "Certaines offres ne sont pas disponibles pour le moment dans votre région App Store."),
    "paywall.yearly.badge": ("Best annual value", "Mejor valor anual", "Выгоднее за год", "Bester Jahrespreis", "Meilleur prix annuel"),
    "paywall.yearly.detail": ("Billed once a year. Auto-renews.", "Se factura una vez al año. Renovación automática.", "Оплата раз в год. Автопродление.", "Einmal jährlich abgerechnet. Verlängert sich automatisch.", "Facturé une fois par an. Renouvellement automatique."),
    "paywall.yearly.trialDetail": ("%1$@ free, then %2$@", "%1$@ gratis y luego %2$@", "%1$@ бесплатно, затем %2$@", "%1$@ kostenlos, danach %2$@", "%1$@ gratuits, puis %2$@"),
    "paywall.yearly.savings": ("%1$@ less than 12 monthly payments of %2$@", "%1$@ menos que 12 pagos mensuales de %2$@", "На %1$@ меньше, чем 12 ежемесячных платежей по %2$@", "%1$@ weniger als 12 Monatszahlungen à %2$@", "%1$@ de moins que 12 paiements mensuels de %2$@"),
    "paywall.monthly.detail": ("Billed monthly. Auto-renews.", "Se factura cada mes. Renovación automática.", "Оплата каждый месяц. Автопродление.", "Monatlich abgerechnet. Verlängert sich automatisch.", "Facturé chaque mois. Renouvellement automatique."),
    "paywall.lifetime.detail": ("One-time purchase. No recurring payments.", "Pago único. Sin pagos recurrentes.", "Разовая покупка. Без регулярных платежей.", "Einmalkauf. Keine wiederkehrenden Zahlungen.", "Achat unique. Aucun paiement récurrent."),
    "paywall.cta.subscribe": ("Subscribe for %@", "Suscribirse por %@", "Подписаться за %@", "Abonnieren für %@", "S’abonner pour %@"),
    "paywall.cta.trial.generic": ("Start free trial", "Iniciar prueba gratuita", "Начать бесплатно", "Kostenlos testen", "Commencer l’essai gratuit"),
    "paywall.cta.lifetime": ("Unlock lifetime access", "Desbloquear acceso de por vida", "Открыть доступ навсегда", "Dauerhaften Zugriff freischalten", "Débloquer l’accès à vie"),
    "paywall.note.lifetime": ("One-time purchase of %@. No recurring payments.", "Pago único de %@. Sin pagos recurrentes.", "Разовая покупка за %@. Без регулярных платежей.", "Einmalkauf für %@. Keine wiederkehrenden Zahlungen.", "Achat unique de %@. Aucun paiement récurrent."),
    "paywall.restore": ("Restore Purchases", "Restaurar compras", "Восстановить покупки", "Käufe wiederherstellen", "Restaurer les achats"),
    "paywall.lifetime.noteTitle": ("About your current subscription", "Sobre tu suscripción actual", "О текущей подписке", "Zu deinem aktuellen Abo", "À propos de votre abonnement actuel"),
    "paywall.lifetime.note": ("This one-time purchase unlocks the app’s features permanently. It doesn’t cancel an existing subscription — to stop its future payments, turn off auto-renew in your Apple subscriptions.",
                              "Este pago único desbloquea las funciones de la app de forma permanente. No cancela una suscripción existente: para detener sus pagos futuros, desactiva la renovación automática en tus suscripciones de Apple.",
                              "Разовая покупка открывает бессрочный доступ в приложении. Она не отменяет действующую подписку. Чтобы прекратить её будущие списания, отключите автопродление в настройках Apple.",
                              "Dieser Einmalkauf schaltet die App-Funktionen dauerhaft frei. Ein bestehendes Abo wird nicht gekündigt – deaktiviere dessen automatische Verlängerung in deinen Apple-Abos.",
                              "Cet achat unique débloque durablement les fonctions de l’app. Il n’annule pas un abonnement existant : pour arrêter ses paiements futurs, désactivez le renouvellement automatique dans vos abonnements Apple."),
    "paywall.lifetime.continue": ("Continue", "Continuar", "Продолжить", "Weiter", "Continuer"),
    "legal.terms": ("Terms of Use", "Términos de uso", "Условия использования", "Nutzungsbedingungen", "Conditions d’utilisation"),
    "legal.privacy": ("Privacy Policy", "Política de privacidad", "Политика конфиденциальности", "Datenschutzerklärung", "Politique de confidentialité"),

    # Purchase results
    "purchase.pending": ("Your purchase is waiting for approval. You’ll get access automatically once it’s approved — no need to buy again.", "Tu compra espera aprobación. Tendrás acceso automáticamente cuando se apruebe; no hace falta volver a comprar.", "Покупка ожидает подтверждения. Доступ откроется автоматически после одобрения — покупать повторно не нужно.", "Dein Kauf wartet auf Genehmigung. Du erhältst den Zugriff automatisch – kein erneuter Kauf nötig.", "Votre achat attend une approbation. L’accès sera automatique une fois approuvé ; inutile de racheter."),
    "purchase.success.monthly": ("Remote Pro is active (monthly). Thank you!", "Remote Pro está activo (mensual). ¡Gracias!", "Remote Pro активен (месяц). Спасибо!", "Remote Pro ist aktiv (monatlich). Danke!", "Remote Pro est actif (mensuel). Merci !"),
    "purchase.success.yearly": ("Remote Pro is active (yearly). Thank you!", "Remote Pro está activo (anual). ¡Gracias!", "Remote Pro активен (год). Спасибо!", "Remote Pro ist aktiv (jährlich). Danke!", "Remote Pro est actif (annuel). Merci !"),
    "purchase.success.lifetime": ("Lifetime access unlocked. Thank you!", "Acceso de por vida desbloqueado. ¡Gracias!", "Доступ навсегда открыт. Спасибо!", "Dauerhafter Zugriff freigeschaltet. Danke!", "Accès à vie débloqué. Merci !"),
    "restore.success": ("Your purchase was restored.", "Tu compra se restauró.", "Покупка восстановлена.", "Dein Kauf wurde wiederhergestellt.", "Votre achat a été restauré."),
    "restore.failed": ("Couldn’t reach the App Store. Check your connection and try again.", "No se pudo conectar con el App Store. Revisa la conexión e inténtalo de nuevo.", "Не удалось связаться с App Store. Проверьте подключение и попробуйте ещё раз.", "Der App Store ist nicht erreichbar. Prüfe die Verbindung und versuche es erneut.", "Impossible de joindre l’App Store. Vérifiez la connexion et réessayez."),
    "restore.nothing": ("No Remote Pro purchase was found for this Apple Account.", "No se encontró ninguna compra de Remote Pro para esta cuenta de Apple.", "Для этого Apple Account покупки Remote Pro не найдены.", "Für diesen Apple Account wurde kein Remote Pro-Kauf gefunden.", "Aucun achat Remote Pro trouvé pour ce compte Apple."),

    # Remote Pro management
    "pro.title": ("Remote Pro", "Remote Pro", "Remote Pro", "Remote Pro", "Remote Pro"),
    "pro.status.inactive": ("Not active", "No activo", "Не активен", "Nicht aktiv", "Inactif"),
    "pro.inactive.neverPurchased": ("You can check your TV for free, then choose a plan.", "Puedes comprobar tu TV gratis y después elegir un plan.", "Проверьте телевизор бесплатно, затем выберите тариф.", "Du kannst deinen Fernseher kostenlos testen und dann einen Tarif wählen.", "Vérifiez gratuitement votre téléviseur, puis choisissez une offre."),
    "pro.inactive.expired": ("Your subscription has ended. Your TVs and settings are kept.", "Tu suscripción terminó. Se conservan tus TV y ajustes.", "Подписка закончилась. Ваши телевизоры и настройки сохранены.", "Dein Abo ist abgelaufen. Fernseher und Einstellungen bleiben erhalten.", "Votre abonnement est terminé. Vos téléviseurs et réglages sont conservés."),
    "pro.inactive.billingRetry": ("Apple couldn’t renew your subscription because of a payment issue.", "Apple no pudo renovar tu suscripción por un problema de pago.", "Apple не удалось продлить подписку из-за проблемы с оплатой.", "Apple konnte dein Abo wegen eines Zahlungsproblems nicht verlängern.", "Apple n’a pas pu renouveler votre abonnement à cause d’un problème de paiement."),
    "pro.inactive.revoked": ("This purchase was refunded or revoked.", "Esta compra se reembolsó o se revocó.", "Покупка возвращена или отозвана.", "Dieser Kauf wurde erstattet oder widerrufen.", "Cet achat a été remboursé ou révoqué."),
    "pro.fixPayment": ("Update payment method", "Actualizar método de pago", "Обновить способ оплаты", "Zahlungsmethode aktualisieren", "Mettre à jour le paiement"),
    "pro.refreshFailed": ("Couldn’t reach the App Store; showing your last verified status.", "No se pudo contactar con el App Store; se muestra tu último estado verificado.", "Не удалось связаться с App Store; показан последний подтверждённый статус.", "App Store nicht erreichbar; zuletzt bestätigter Status wird angezeigt.", "App Store injoignable ; affichage du dernier statut vérifié."),
    "pro.lifetime.status": ("Purchased · Lifetime access", "Comprado · Acceso de por vida", "Куплено · Доступ навсегда", "Gekauft · Dauerhafter Zugriff", "Acheté · Accès à vie"),
    "pro.trial.until": ("Free period until %@.", "Periodo gratuito hasta el %@.", "Бесплатный период до %@.", "Kostenloser Zeitraum bis %@.", "Période gratuite jusqu’au %@."),
    "pro.discount.until": ("Discounted period until %@.", "Periodo con descuento hasta el %@.", "Период со скидкой до %@.", "Rabattzeitraum bis %@.", "Période à prix réduit jusqu’au %@."),
    "pro.gracePeriod": ("Apple couldn’t take the last payment. Your access continues for now — please update your payment method.", "Apple no pudo cobrar el último pago. Mantienes el acceso por ahora; actualiza tu método de pago.", "Apple не удалось провести последний платёж. Доступ пока сохраняется — обновите способ оплаты.", "Apple konnte die letzte Zahlung nicht einziehen. Dein Zugriff bleibt vorerst – bitte aktualisiere die Zahlungsmethode.", "Apple n’a pas pu prélever le dernier paiement. Votre accès continue pour l’instant : mettez à jour votre moyen de paiement."),
    "pro.autoRenewOff": ("Auto-renew is off. Access continues until %@.", "La renovación automática está desactivada. El acceso sigue hasta el %@.", "Автопродление выключено. Доступ действует до %@.", "Automatische Verlängerung ist aus. Zugriff bis %@.", "Renouvellement désactivé. Accès jusqu’au %@."),
    "pro.nextPayment": ("Next payment: %@", "Próximo pago: %@", "Следующий платёж: %@", "Nächste Zahlung: %@", "Prochain paiement : %@"),
    "pro.renewalUnknown": ("Renewal date is syncing with the App Store.", "La fecha de renovación se está sincronizando con el App Store.", "Дата продления синхронизируется с App Store.", "Das Verlängerungsdatum wird mit dem App Store abgeglichen.", "La date de renouvellement se synchronise avec l’App Store."),
    "pro.scheduledChange": ("Switches to %1$@ on %2$@ (%3$@).", "Cambia a %1$@ el %2$@ (%3$@).", "Переход на тариф «%1$@» %2$@ (%3$@).", "Wechsel zu %1$@ am %2$@ (%3$@).", "Passage à %1$@ le %2$@ (%3$@)."),
    "pro.lifetime.oldSubscriptionRenewing": ("Your %@ subscription is still set to renew. Lifetime access doesn’t cancel it — turn off auto-renew in your Apple subscriptions if you no longer want it.", "Tu suscripción %@ aún se renovará. El acceso de por vida no la cancela: desactiva la renovación en tus suscripciones de Apple si ya no la quieres.", "Подписка («%@») всё ещё продлевается. Доступ навсегда её не отменяет — отключите автопродление в подписках Apple, если она больше не нужна.", "Dein %@-Abo verlängert sich weiterhin. Der dauerhafte Zugriff kündigt es nicht – deaktiviere die Verlängerung in deinen Apple-Abos, wenn du es nicht mehr brauchst.", "Votre abonnement %@ est toujours reconduit. L’accès à vie ne l’annule pas : désactivez le renouvellement dans vos abonnements Apple si vous n’en voulez plus."),
    "pro.lifetime.oldSubscriptionOff": ("Your previous subscription won’t renew.", "Tu suscripción anterior no se renovará.", "Предыдущая подписка не будет продлена.", "Dein vorheriges Abo verlängert sich nicht.", "Votre ancien abonnement ne sera pas renouvelé."),
    "pro.lifetime.oldSubscriptionUnknown": ("You may still have a subscription. Check it in your Apple subscriptions.", "Puede que aún tengas una suscripción. Revísala en tus suscripciones de Apple.", "Возможно, у вас ещё есть подписка. Проверьте её в подписках Apple.", "Eventuell hast du noch ein Abo. Prüfe es in deinen Apple-Abos.", "Vous avez peut-être encore un abonnement. Vérifiez-le dans vos abonnements Apple."),
    "pro.manageExisting": ("Manage existing subscription", "Gestionar la suscripción existente", "Управлять текущей подпиской", "Bestehendes Abo verwalten", "Gérer l’abonnement existant"),
    "pro.fromCache": ("Shown from your last verified purchase while the App Store is unreachable.", "Se muestra tu última compra verificada mientras el App Store no está disponible.", "Показаны данные последней подтверждённой покупки, пока App Store недоступен.", "Angezeigt aus deinem zuletzt bestätigten Kauf, solange der App Store nicht erreichbar ist.", "Affiché d’après votre dernier achat vérifié tant que l’App Store est injoignable."),
    "pro.actions": ("Your plan", "Tu plan", "Ваш тариф", "Dein Tarif", "Votre offre"),
    "pro.seePlans": ("See plans", "Ver planes", "Посмотреть тарифы", "Tarife ansehen", "Voir les offres"),
    "pro.changeToYearly": ("Change to yearly", "Cambiar a anual", "Перейти на год", "Zu jährlich wechseln", "Passer à l’annuel"),
    "pro.buyLifetime": ("Buy lifetime access", "Comprar acceso de por vida", "Купить доступ навсегда", "Dauerhaften Zugriff kaufen", "Acheter l’accès à vie"),
    "pro.manage": ("Manage subscription", "Gestionar suscripción", "Управлять подпиской", "Abo verwalten", "Gérer l’abonnement"),
    "pro.purchaseHelp": ("Help with purchases", "Ayuda con compras", "Помощь с покупками", "Hilfe zu Käufen", "Aide sur les achats"),
    "pro.redeemCode": ("Redeem an offer code", "Canjear un código de oferta", "Активировать промокод", "Angebotscode einlösen", "Utiliser un code d’offre"),
    "pro.sameFeatures": ("All plans include the same features on all your supported TVs.", "Todos los planes incluyen las mismas funciones en todas tus TV compatibles.", "Все тарифы включают одинаковые функции на всех ваших совместимых ТВ.", "Alle Tarife enthalten dieselben Funktionen für alle unterstützten Fernseher.", "Toutes les offres incluent les mêmes fonctions sur tous vos téléviseurs pris en charge."),

    # Change plan
    "change.title": ("Change plan", "Cambiar plan", "Смена тарифа", "Tarif wechseln", "Changer d’offre"),
    "change.yearly.savings": ("%1$@ per year — %2$@ less than 12 payments of %3$@ (about %4$lld%% savings).", "%1$@ al año: %2$@ menos que 12 pagos de %3$@ (un ahorro de aprox. el %4$lld %%).", "%1$@ в год — на %2$@ меньше, чем 12 платежей по %3$@ (экономия около %4$lld%%).", "%1$@ pro Jahr – %2$@ weniger als 12 Zahlungen à %3$@ (ca. %4$lld %% Ersparnis).", "%1$@ par an — %2$@ de moins que 12 paiements de %3$@ (environ %4$lld %% d’économie)."),
    "change.yearly.monthlyEquivalent": ("That’s about %@ per month, paid as one yearly payment.", "Equivale a unos %@ al mes, pagados en un único pago anual.", "Это примерно %@ в месяц при оплате одним годовым платежом.", "Das sind etwa %@ pro Monat, bezahlt als eine Jahreszahlung.", "Soit environ %@ par mois, réglés en un paiement annuel."),
    "change.yearly.timing": ("Apple switches your plan at your next renewal. Your monthly access continues until then. No new free trial comes with the change.", "Apple cambia tu plan en la próxima renovación. Tu acceso mensual continúa hasta entonces. El cambio no incluye una nueva prueba gratuita.", "Apple сменит тариф при следующем продлении. До этого действует месячный доступ. Новый пробный период при смене не предоставляется.", "Apple wechselt deinen Tarif bei der nächsten Verlängerung. Bis dahin läuft der Monatszugang weiter. Eine neue Testphase gibt es dabei nicht.", "Apple change votre offre au prochain renouvellement. Votre accès mensuel continue d’ici là. Aucun nouvel essai gratuit n’est inclus."),
    "change.yearly.timingTrial": ("You’re in a free or discounted period. Apple decides how the change applies; remaining free days may not carry over. Check the date Apple confirms.", "Estás en un periodo gratuito o con descuento. Apple decide cómo se aplica el cambio; los días gratis restantes pueden no conservarse. Revisa la fecha que confirme Apple.", "У вас бесплатный период или период со скидкой. Как применится смена, решает Apple; оставшиеся бесплатные дни могут не перенестись. Проверьте дату, которую подтвердит Apple.", "Du bist in einem kostenlosen oder rabattierten Zeitraum. Apple entscheidet, wie der Wechsel gilt; übrige Gratistage werden eventuell nicht übernommen. Prüfe das von Apple bestätigte Datum.", "Vous êtes en période gratuite ou à prix réduit. Apple décide de l’application du changement ; les jours gratuits restants peuvent ne pas être conservés. Vérifiez la date confirmée par Apple."),
    "change.yearly.confirm": ("Change to yearly", "Cambiar a anual", "Перейти на год", "Zu jährlich wechseln", "Passer à l’annuel"),
    "change.yearly.scheduled": ("Confirmed by Apple. Your plan changes at the next renewal — see the date above.", "Confirmado por Apple. Tu plan cambia en la próxima renovación; consulta la fecha arriba.", "Подтверждено Apple. Тариф сменится при следующем продлении — дата указана выше.", "Von Apple bestätigt. Dein Tarif wechselt bei der nächsten Verlängerung – siehe Datum oben.", "Confirmé par Apple. Votre offre change au prochain renouvellement : voir la date ci-dessus."),
    "change.yearly.syncing": ("Apple accepted the request; the new schedule is still syncing.", "Apple aceptó la solicitud; el nuevo calendario aún se está sincronizando.", "Apple принял запрос; новое расписание ещё синхронизируется.", "Apple hat die Anfrage angenommen; der neue Zeitplan wird noch abgeglichen.", "Apple a accepté la demande ; le nouveau calendrier se synchronise encore."),
    "change.lifetime.detail": ("Same features, no recurring payments. Earlier payments aren’t deducted from the price.", "Mismas funciones, sin pagos recurrentes. Los pagos anteriores no se descuentan del precio.", "Те же функции без регулярных платежей. Прошлые платежи не вычитаются из цены.", "Gleiche Funktionen, keine wiederkehrenden Zahlungen. Frühere Zahlungen werden nicht angerechnet.", "Mêmes fonctions, sans paiement récurrent. Les paiements antérieurs ne sont pas déduits du prix."),
    "change.lifetime.done": ("Lifetime access is active. Remember to manage your existing subscription if you don’t want it to renew.", "El acceso de por vida está activo. Recuerda gestionar tu suscripción actual si no quieres que se renueve.", "Доступ навсегда активен. Не забудьте управлять текущей подпиской, если не хотите её продления.", "Dauerhafter Zugriff ist aktiv. Verwalte dein bestehendes Abo, wenn es sich nicht verlängern soll.", "L’accès à vie est actif. Pensez à gérer votre abonnement existant si vous ne souhaitez pas le renouveler."),

    # Trial reminder notification
    "notification.trial.title": ("Your free period ends soon", "Tu periodo gratuito termina pronto", "Бесплатный период скоро закончится", "Dein kostenloser Zeitraum endet bald", "Votre période gratuite se termine bientôt"),
    "notification.trial.body": ("It ends on %@. You can manage it in your Apple subscriptions.", "Termina el %@. Puedes gestionarlo en tus suscripciones de Apple.", "Он закончится %@. Управлять им можно в подписках Apple.", "Er endet am %@. Du kannst ihn in deinen Apple-Abos verwalten.", "Elle se termine le %@. Vous pouvez la gérer dans vos abonnements Apple."),
    "notification.trial.body.price": ("It ends on %1$@. Then %2$@ unless you cancel at least 24 hours before.", "Termina el %1$@. Después, %2$@ salvo que canceles al menos 24 horas antes.", "Он закончится %1$@. Затем — %2$@, если не отменить минимум за 24 часа.", "Er endet am %1$@. Danach %2$@, sofern du nicht mindestens 24 Stunden vorher kündigst.", "Elle se termine le %1$@. Ensuite %2$@, sauf résiliation au moins 24 heures avant."),

    # Bonus
    "bonus.title": ("Welcome bonus", "Bono de bienvenida", "Приветственный бонус", "Willkommensbonus", "Bonus de bienvenue"),
    "bonus.unavailable.title": ("No offers right now", "No hay ofertas ahora", "Сейчас предложений нет", "Gerade keine Angebote", "Aucune offre pour le moment"),
    "bonus.unavailable.message": ("There’s no active bonus campaign. Standard plans are always available in Remote Pro.", "No hay ninguna campaña activa. Los planes estándar siempre están en Remote Pro.", "Активной бонусной акции нет. Обычные тарифы всегда доступны в Remote Pro.", "Es läuft keine Bonusaktion. Standardtarife findest du immer unter Remote Pro.", "Aucune campagne de bonus active. Les offres standard sont toujours disponibles dans Remote Pro."),
    "bonus.invite.title": ("A bonus for you", "Un bono para ti", "Бонус для вас", "Ein Bonus für dich", "Un bonus pour vous"),
    "bonus.invite.message": ("Spin once for free to get a subscription offer. Spinning doesn’t buy anything or start a subscription.", "Gira una vez gratis para obtener una oferta de suscripción. Girar no compra nada ni inicia una suscripción.", "Крутите один раз бесплатно, чтобы получить предложение подписки. Вращение ничего не покупает и не оформляет подписку.", "Dreh einmal kostenlos für ein Abo-Angebot. Das Drehen kauft nichts und startet kein Abo.", "Tournez une fois gratuitement pour obtenir une offre d’abonnement. Tourner n’achète rien et ne démarre aucun abonnement."),
    "bonus.odds": ("Each of the %lld bonuses below has an equal chance.", "Cada uno de los %lld bonos tiene la misma probabilidad.", "У каждого из %lld бонусов ниже одинаковый шанс.", "Jeder der %lld Boni unten hat die gleiche Chance.", "Chacun des %lld bonus ci-dessous a la même probabilité."),
    "bonus.sector.discount": ("%lld%% off the first month", "%lld %% de descuento el primer mes", "Скидка %lld%% на первый месяц", "%lld %% Rabatt im ersten Monat", "%lld %% de réduction le premier mois"),
    "bonus.sector.freeWeek": ("7 days free", "7 días gratis", "7 дней бесплатно", "7 Tage kostenlos", "7 jours gratuits"),
    "bonus.sector.freeWeek.short": ("7 days", "7 días", "7 дней", "7 Tage", "7 jours"),
    "bonus.terms.short": ("Offers are activated through Apple and apply only if Apple’s conditions are met. Discounts apply to the first month only; subscriptions then renew at the standard price until canceled.", "Las ofertas se activan a través de Apple y solo se aplican si se cumplen sus condiciones. Los descuentos son solo para el primer mes; después la suscripción se renueva al precio estándar hasta que canceles.", "Предложения активируются через Apple и действуют только при выполнении условий Apple. Скидки — только на первый месяц; затем подписка продлевается по стандартной цене до отмены.", "Angebote werden über Apple aktiviert und gelten nur, wenn Apples Bedingungen erfüllt sind. Rabatte gelten nur im ersten Monat; danach verlängert sich das Abo zum Standardpreis bis zur Kündigung.", "Les offres s’activent via Apple et ne s’appliquent que si les conditions d’Apple sont remplies. Les réductions ne valent que pour le premier mois ; l’abonnement se renouvelle ensuite au prix standard jusqu’à résiliation."),
    "bonus.rules": ("Full promotion rules", "Reglas completas de la promoción", "Полные правила акции", "Vollständige Aktionsbedingungen", "Règlement complet"),
    "bonus.spin": ("Spin", "Girar", "Крутить", "Drehen", "Tourner"),
    "bonus.spin.hint": ("Reveals your saved bonus", "Muestra tu bono guardado", "Показывает ваш сохранённый бонус", "Zeigt deinen gespeicherten Bonus", "Révèle votre bonus enregistré"),
    "bonus.noThanks": ("No thanks", "No, gracias", "Нет, спасибо", "Nein danke", "Non merci"),
    "bonus.soldOut": ("No bonuses are available right now.", "No hay bonos disponibles ahora.", "Сейчас бонусов нет.", "Gerade sind keine Boni verfügbar.", "Aucun bonus disponible pour le moment."),
    "bonus.result.title": ("Your bonus", "Tu bono", "Ваш бонус", "Dein Bonus", "Votre bonus"),
    "bonus.discount.prices": ("%1$@ for the first month, then %2$@ per month.", "%1$@ el primer mes y luego %2$@ al mes.", "%1$@ за первый месяц, затем %2$@ в месяц.", "%1$@ im ersten Monat, danach %2$@ pro Monat.", "%1$@ le premier mois, puis %2$@ par mois."),
    "bonus.discount.standard": ("After the first month: %@ per month.", "Tras el primer mes: %@ al mes.", "После первого месяца: %@ в месяц.", "Nach dem ersten Monat: %@ pro Monat.", "Après le premier mois : %@ par mois."),
    "bonus.discount.firstMonthOnly": ("The discount applies to the first month of the monthly plan only — not to renewals, the yearly plan or lifetime access.", "El descuento se aplica solo al primer mes del plan mensual, no a las renovaciones, al plan anual ni al acceso de por vida.", "Скидка действует только на первый месяц месячного тарифа — не на продления, годовой тариф или доступ навсегда.", "Der Rabatt gilt nur für den ersten Monat des Monatstarifs – nicht für Verlängerungen, den Jahrestarif oder den dauerhaften Zugriff.", "La réduction ne vaut que pour le premier mois de l’offre mensuelle, pas pour les renouvellements, l’annuel ni l’accès à vie."),
    "bonus.autoRenew": ("The subscription renews automatically until you cancel.", "La suscripción se renueva automáticamente hasta que canceles.", "Подписка продлевается автоматически до отмены.", "Das Abo verlängert sich automatisch bis zur Kündigung.", "L’abonnement se renouvelle automatiquement jusqu’à résiliation."),
    "bonus.freeWeek.then": ("After 7 days", "Después de 7 días", "После 7 дней", "Nach 7 Tagen", "Après 7 jours"),
    "bonus.freeWeek.then.monthly": ("Then monthly", "Luego mensual", "Затем помесячно", "Dann monatlich", "Puis mensuel"),
    "bonus.freeWeek.then.yearly": ("Then yearly", "Luego anual", "Затем ежегодно", "Dann jährlich", "Puis annuel"),
    "bonus.freeWeek.onlyPlan": ("This bonus is available with the %@ plan.", "Este bono está disponible con el plan %@.", "Этот бонус доступен с тарифом «%@».", "Dieser Bonus gilt für den Tarif %@.", "Ce bonus est disponible avec l’offre %@."),
    "bonus.freeWeek.summary": ("7 days free, then %@.", "7 días gratis y luego %@.", "7 дней бесплатно, затем %@.", "7 Tage kostenlos, danach %@.", "7 jours gratuits, puis %@."),
    "bonus.freeWeek.cancel": ("Cancel at least 24 hours before the free period ends to avoid being charged.", "Cancela al menos 24 horas antes de que termine el periodo gratuito para que no se te cobre.", "Отмените не позднее чем за 24 часа до конца бесплатного периода, чтобы избежать списания.", "Kündige mindestens 24 Stunden vor Ende des Gratiszeitraums, um eine Abbuchung zu vermeiden.", "Annulez au moins 24 heures avant la fin de la période gratuite pour éviter d’être facturé."),
    "bonus.freeWeek.notAdditional": ("These 7 days replace the standard 3-day trial; they aren’t added to it.", "Estos 7 días sustituyen a la prueba estándar de 3 días; no se suman.", "Эти 7 дней заменяют стандартные 3 дня пробного периода, а не добавляются к ним.", "Diese 7 Tage ersetzen den normalen 3‑Tage-Test; sie kommen nicht hinzu.", "Ces 7 jours remplacent l’essai standard de 3 jours ; ils ne s’y ajoutent pas."),
    "bonus.activate": ("Activate offer", "Activar oferta", "Активировать предложение", "Angebot aktivieren", "Activer l’offre"),
    "bonus.awaitingApple": ("Complete the redemption in the App Store. Access starts once Apple confirms the transaction.", "Completa el canje en el App Store. El acceso empieza cuando Apple confirme la transacción.", "Завершите активацию в App Store. Доступ откроется после подтверждения транзакции Apple.", "Schließe die Einlösung im App Store ab. Der Zugriff startet, sobald Apple die Transaktion bestätigt.", "Terminez l’utilisation du code dans l’App Store. L’accès démarre dès qu’Apple confirme la transaction."),
    "bonus.checkAgain": ("Check again", "Comprobar de nuevo", "Проверить снова", "Erneut prüfen", "Vérifier à nouveau"),
    "bonus.appleConditions": ("Apple decides whether the offer applies to your Apple Account.", "Apple decide si la oferta se aplica a tu cuenta de Apple.", "Применимость предложения к вашему Apple Account определяет Apple.", "Apple entscheidet, ob das Angebot für deinen Apple Account gilt.", "Apple décide si l’offre s’applique à votre compte Apple."),
    "bonus.standardPlans": ("See standard plans instead", "Ver planes estándar", "Посмотреть обычные тарифы", "Stattdessen Standardtarife ansehen", "Voir plutôt les offres standard"),
    "bonus.verified": ("Offer activated by Apple on %@.", "Oferta activada por Apple el %@.", "Предложение активировано Apple %@.", "Angebot von Apple am %@ aktiviert.", "Offre activée par Apple le %@."),
}

PLURALS = {
    "period.days": {
        "en": {"one": "%lld day", "other": "%lld days"},
        "es": {"one": "%lld día", "other": "%lld días"},
        "ru": {"one": "%lld день", "few": "%lld дня", "many": "%lld дней", "other": "%lld дня"},
        "de": {"one": "%lld Tag", "other": "%lld Tage"},
        "fr": {"one": "%lld jour", "many": "%lld jours", "other": "%lld jours"},
    },
    "period.weeks": {
        "en": {"one": "%lld week", "other": "%lld weeks"},
        "es": {"one": "%lld semana", "other": "%lld semanas"},
        "ru": {"one": "%lld неделя", "few": "%lld недели", "many": "%lld недель", "other": "%lld недели"},
        "de": {"one": "%lld Woche", "other": "%lld Wochen"},
        "fr": {"one": "%lld semaine", "many": "%lld semaines", "other": "%lld semaines"},
    },
    "period.months": {
        "en": {"one": "%lld month", "other": "%lld months"},
        "es": {"one": "%lld mes", "other": "%lld meses"},
        "ru": {"one": "%lld месяц", "few": "%lld месяца", "many": "%lld месяцев", "other": "%lld месяца"},
        "de": {"one": "%lld Monat", "other": "%lld Monate"},
        "fr": {"one": "%lld mois", "many": "%lld mois", "other": "%lld mois"},
    },
    "period.years": {
        "en": {"one": "%lld year", "other": "%lld years"},
        "es": {"one": "%lld año", "other": "%lld años"},
        "ru": {"one": "%lld год", "few": "%lld года", "many": "%lld лет", "other": "%lld года"},
        "de": {"one": "%lld Jahr", "other": "%lld Jahre"},
        "fr": {"one": "%lld an", "many": "%lld ans", "other": "%lld ans"},
    },
    "paywall.cta.trial.days": {
        "en": {"one": "Start %lld-day free trial", "other": "Start %lld-day free trial"},
        "es": {"one": "Iniciar prueba gratuita de %lld día", "other": "Iniciar prueba gratuita de %lld días"},
        "ru": {"one": "Попробовать %lld день бесплатно", "few": "Попробовать %lld дня бесплатно", "many": "Попробовать %lld дней бесплатно", "other": "Попробовать %lld дня бесплатно"},
        "de": {"one": "%lld Tag kostenlos testen", "other": "%lld Tage kostenlos testen"},
        "fr": {"one": "Commencer l’essai gratuit de %lld jour", "many": "Commencer l’essai gratuit de %lld jours", "other": "Commencer l’essai gratuit de %lld jours"},
    },
    "paywall.cta.trial.months": {
        "en": {"one": "Start %lld-month free trial", "other": "Start %lld-month free trial"},
        "es": {"one": "Iniciar prueba gratuita de %lld mes", "other": "Iniciar prueba gratuita de %lld meses"},
        "ru": {"one": "Попробовать %lld месяц бесплатно", "few": "Попробовать %lld месяца бесплатно", "many": "Попробовать %lld месяцев бесплатно", "other": "Попробовать %lld месяца бесплатно"},
        "de": {"one": "%lld Monat kostenlos testen", "other": "%lld Monate kostenlos testen"},
        "fr": {"one": "Commencer l’essai gratuit de %lld mois", "many": "Commencer l’essai gratuit de %lld mois", "other": "Commencer l’essai gratuit de %lld mois"},
    },
}
