# Localization source: Cast tab, photos/videos, Screen Mirroring.
# Tuple order: (en, es, ru, de, fr).

STRINGS = {
    "cast.connectFirst": ("Connect a TV to show photos or your screen.", "Conecta una TV para mostrar fotos o tu pantalla.", "Подключите телевизор, чтобы показать фото или экран.", "Verbinde einen Fernseher, um Fotos oder deinen Bildschirm zu zeigen.", "Connectez un téléviseur pour afficher des photos ou votre écran."),
    "cast.photos.title": ("Photos & Videos", "Fotos y vídeos", "Фото и видео", "Fotos & Videos", "Photos et vidéos"),
    "cast.photos.subtitle": ("Show chosen photos and home videos on the TV", "Muestra en la TV las fotos y vídeos que elijas", "Показывайте выбранные фото и домашние видео на ТВ", "Ausgewählte Fotos und Videos auf dem Fernseher zeigen", "Affichez les photos et vidéos choisies sur le téléviseur"),
    "cast.mirroring.title": ("Screen Mirroring", "Duplicar pantalla", "Трансляция экрана", "Bildschirm spiegeln", "Recopie de l’écran"),
    "cast.mirroring.subtitle": ("Show your iPhone screen on a compatible TV", "Muestra la pantalla del iPhone en una TV compatible", "Показ экрана iPhone на совместимом ТВ", "iPhone-Bildschirm auf einem kompatiblen Fernseher zeigen", "Affichez l’écran de l’iPhone sur un téléviseur compatible"),
    "cast.photos.unsupported": ("This TV didn’t offer a media receiver, so photos and videos may not work.", "Esta TV no ofreció un receptor multimedia; puede que las fotos y vídeos no funcionen.", "Телевизор не предоставил медиаприёмник, поэтому фото и видео могут не работать.", "Dieser Fernseher bietet keinen Medienempfänger, Fotos und Videos funktionieren eventuell nicht.", "Ce téléviseur n’a pas de récepteur multimédia : photos et vidéos peuvent ne pas fonctionner."),
    "cast.choose": ("Choose photos or videos", "Elegir fotos o vídeos", "Выбрать фото или видео", "Fotos oder Videos wählen", "Choisir des photos ou vidéos"),
    "cast.chooseOther": ("Choose other items", "Elegir otros elementos", "Выбрать другие", "Andere wählen", "Choisir d’autres éléments"),
    "cast.pickerPrivacy": ("Only the items you pick are shared with the app — no full library access is needed.", "Solo se comparten con la app los elementos que elijas; no se necesita acceso a toda la fototeca.", "Приложение получает только выбранные вами файлы — доступ ко всей медиатеке не нужен.", "Nur die gewählten Objekte werden mit der App geteilt – kein Vollzugriff auf die Mediathek nötig.", "Seuls les éléments choisis sont partagés avec l’app ; aucun accès complet à la photothèque n’est requis."),
    "cast.loading": ("Getting your items…", "Obteniendo los elementos…", "Загружаем файлы…", "Objekte werden geladen …", "Récupération des éléments…"),
    "cast.loading.detail": ("Items stored in iCloud are downloaded first.", "Los elementos de iCloud se descargan primero.", "Файлы из iCloud сначала загружаются.", "Objekte aus iCloud werden zuerst geladen.", "Les éléments stockés dans iCloud sont d’abord téléchargés."),
    "cast.preview.photo": ("Photo preview", "Vista previa de la foto", "Предпросмотр фото", "Fotovorschau", "Aperçu de la photo"),
    "cast.preview.video": ("Video preview", "Vista previa del vídeo", "Предпросмотр видео", "Videovorschau", "Aperçu de la vidéo"),
    "cast.previous": ("Previous item", "Elemento anterior", "Предыдущий", "Vorheriges Objekt", "Élément précédent"),
    "cast.next": ("Next item", "Elemento siguiente", "Следующий", "Nächstes Objekt", "Élément suivant"),
    "cast.position": ("%1$lld of %2$lld", "%1$lld de %2$lld", "%1$lld из %2$lld", "%1$lld von %2$lld", "%1$lld sur %2$lld"),
    "cast.fitMode": ("Photo size", "Tamaño de la foto", "Размер фото", "Fotogröße", "Taille de la photo"),
    "cast.fit": ("Fit", "Ajustar", "Целиком", "Einpassen", "Ajuster"),
    "cast.fill": ("Fill", "Rellenar", "Заполнить", "Füllen", "Remplir"),
    "cast.fit.detail": ("The whole photo is shown; the TV may add bars.", "Se muestra la foto completa; la TV puede añadir bandas.", "Фото показывается целиком; по краям могут быть полосы.", "Das ganze Foto wird gezeigt; der Fernseher kann Balken ergänzen.", "La photo entière est affichée ; le téléviseur peut ajouter des bandes."),
    "cast.fill.detail": ("The photo fills the screen; edges are cropped to 16:9.", "La foto llena la pantalla; los bordes se recortan a 16:9.", "Фото заполняет экран; края обрезаются до 16:9.", "Das Foto füllt den Bildschirm; die Ränder werden auf 16:9 zugeschnitten.", "La photo remplit l’écran ; les bords sont recadrés en 16:9."),
    "cast.showOnTV": ("Show on TV", "Mostrar en TV", "Показать на ТВ", "Auf dem Fernseher anzeigen", "Afficher sur le téléviseur"),
    "cast.preparing": ("Preparing video for the TV…", "Preparando el vídeo para la TV…", "Подготавливаем видео для ТВ…", "Video wird für den Fernseher vorbereitet …", "Préparation de la vidéo pour le téléviseur…"),
    "cast.onTV": ("Showing on the TV", "Mostrando en la TV", "Показывается на ТВ", "Wird auf dem Fernseher gezeigt", "Affiché sur le téléviseur"),
    "cast.stop": ("Stop showing", "Dejar de mostrar", "Остановить показ", "Anzeige beenden", "Arrêter l’affichage"),
    "cast.slideshow": ("Slideshow", "Presentación", "Слайд-шоу", "Diashow", "Diaporama"),
    "cast.slideshow.interval": ("Interval", "Intervalo", "Интервал", "Intervall", "Intervalle"),
    "cast.slideshow.seconds": ("%lld s", "%lld s", "%lld с", "%lld s", "%lld s"),
    "cast.video.proOnly": ("Videos are part of Remote Pro.", "Los vídeos forman parte de Remote Pro.", "Видео входит в Remote Pro.", "Videos gehören zu Remote Pro.", "Les vidéos font partie de Remote Pro."),
    "cast.video.progress": ("Playback position", "Posición de reproducción", "Позиция воспроизведения", "Wiedergabeposition", "Position de lecture"),
    "cast.video.back15": ("Back 15 seconds", "Retroceder 15 segundos", "Назад на 15 секунд", "15 Sekunden zurück", "Reculer de 15 secondes"),
    "cast.video.forward15": ("Forward 15 seconds", "Avanzar 15 segundos", "Вперёд на 15 секунд", "15 Sekunden vor", "Avancer de 15 secondes"),
    "cast.video.noStatus": ("This TV doesn’t report playback progress.", "Esta TV no informa del progreso de reproducción.", "Телевизор не сообщает о ходе воспроизведения.", "Dieser Fernseher meldet keinen Wiedergabefortschritt.", "Ce téléviseur n’indique pas la progression de la lecture."),

    # Mirroring
    "mirroring.setup.tv": ("TV", "TV", "Телевизор", "Fernseher", "Téléviseur"),
    "mirroring.setup.receiver": ("Receiver", "Receptor", "Приёмник", "Empfänger", "Récepteur"),
    "mirroring.setup.receiver.browser": ("TV web browser", "Navegador de la TV", "Браузер телевизора", "Webbrowser des Fernsehers", "Navigateur du téléviseur"),
    "mirroring.setup.receiver.missing": ("Not available", "No disponible", "Недоступен", "Nicht verfügbar", "Indisponible"),
    "mirroring.setup.network": ("Network", "Red", "Сеть", "Netzwerk", "Réseau"),
    "mirroring.setup.network.ok": ("Wi‑Fi connected", "Wi‑Fi conectado", "Wi‑Fi подключён", "WLAN verbunden", "Wi‑Fi connecté"),
    "mirroring.setup.network.none": ("No Wi‑Fi", "Sin Wi‑Fi", "Нет Wi‑Fi", "Kein WLAN", "Pas de Wi‑Fi"),
    "mirroring.unsupportedPlatform": ("Our Screen Mirroring isn’t available for this TV because it has no web browser we can use. Remote control and other supported features still work.",
                                      "Nuestra duplicación no está disponible para esta TV porque no tiene un navegador utilizable. El mando y otras funciones compatibles siguen funcionando.",
                                      "Наша трансляция экрана недоступна для этого телевизора: у него нет подходящего браузера. Пульт и другие поддерживаемые функции работают.",
                                      "Unsere Spiegelung ist für diesen Fernseher nicht verfügbar, da er keinen nutzbaren Webbrowser hat. Fernbedienung und andere Funktionen bleiben nutzbar.",
                                      "Notre recopie n’est pas disponible pour ce téléviseur, faute de navigateur utilisable. La télécommande et les autres fonctions prises en charge fonctionnent."),
    "mirroring.howItWorks": ("When you start, iOS asks for permission to record the screen. We then open a private page in the TV’s web browser that shows your screen over your Wi‑Fi.",
                             "Al empezar, iOS pide permiso para grabar la pantalla. Después abrimos una página privada en el navegador de la TV que muestra tu pantalla por tu Wi‑Fi.",
                             "При запуске iOS запросит разрешение на запись экрана. Затем мы откроем в браузере телевизора закрытую страницу, которая показывает ваш экран через Wi‑Fi.",
                             "Beim Start fragt iOS nach der Erlaubnis zur Bildschirmaufnahme. Dann öffnen wir im Webbrowser des Fernsehers eine private Seite, die deinen Bildschirm über dein WLAN zeigt.",
                             "Au démarrage, iOS demande l’autorisation d’enregistrer l’écran. Nous ouvrons ensuite une page privée dans le navigateur du téléviseur qui affiche votre écran via le Wi‑Fi."),
    "mirroring.privacyWarning": ("Everything on your iPhone screen may appear on the TV, including notifications and personal content.",
                                 "Todo lo que aparezca en la pantalla del iPhone puede verse en la TV, incluidas notificaciones y contenido personal.",
                                 "Всё, что на экране iPhone, может появиться на телевизоре, включая уведомления и личные данные.",
                                 "Alles auf deinem iPhone-Bildschirm kann auf dem Fernseher erscheinen, auch Mitteilungen und persönliche Inhalte.",
                                 "Tout ce qui s’affiche sur l’iPhone peut apparaître sur le téléviseur, y compris les notifications et le contenu personnel."),
    "mirroring.limits": ("Picture only, no sound. Delay is noticeable, so it’s not meant for games. Many streaming apps block capture and show black.",
                         "Solo imagen, sin sonido. El retraso es perceptible, no está pensado para juegos. Muchas apps de streaming bloquean la captura y se ven en negro.",
                         "Только изображение, без звука. Задержка заметна, поэтому режим не для игр. Многие стриминговые приложения блокируют захват — будет чёрный экран.",
                         "Nur Bild, kein Ton. Die Verzögerung ist spürbar, daher nicht für Spiele gedacht. Viele Streaming-Apps blockieren die Aufnahme und zeigen Schwarz.",
                         "Image seule, sans son. Le délai est perceptible : ce n’est pas prévu pour les jeux. Beaucoup d’apps de streaming bloquent la capture et affichent du noir."),
    "mirroring.start": ("Start Screen Mirroring", "Iniciar duplicación", "Начать трансляцию", "Spiegelung starten", "Démarrer la recopie"),
    "mirroring.start.systemPrompt": ("iOS will show a confirmation before anything is shared.", "iOS mostrará una confirmación antes de compartir nada.", "iOS покажет подтверждение, прежде чем что-либо будет передано.", "iOS zeigt eine Bestätigung, bevor etwas geteilt wird.", "iOS affichera une confirmation avant tout partage."),
    "mirroring.status.waiting": ("Connecting to the TV…", "Conectando con la TV…", "Подключение к телевизору…", "Verbindung zum Fernseher …", "Connexion au téléviseur…"),
    "mirroring.status.waiting.detail": ("The TV browser is opening. If nothing appears within a minute, check the TV screen.", "Se está abriendo el navegador de la TV. Si no aparece nada en un minuto, revisa la TV.", "Открывается браузер на телевизоре. Если в течение минуты ничего не появится, проверьте экран телевизора.", "Der TV-Browser wird geöffnet. Erscheint nach einer Minute nichts, prüfe den Fernseher.", "Le navigateur du téléviseur s’ouvre. Si rien n’apparaît dans la minute, vérifiez le téléviseur."),
    "mirroring.status.live": ("Mirroring to the TV", "Duplicando en la TV", "Идёт трансляция на ТВ", "Spiegelung auf den Fernseher", "Recopie vers le téléviseur"),
    "mirroring.duration": ("Duration: %@", "Duración: %@", "Длительность: %@", "Dauer: %@", "Durée : %@"),
    "mirroring.latency": ("Measured round trip: %lld ms", "Ida y vuelta medida: %lld ms", "Измеренная задержка туда-обратно: %lld мс", "Gemessene Umlaufzeit: %lld ms", "Aller-retour mesuré : %lld ms"),
    "mirroring.resolution": ("Picture: %1$lld × %2$lld", "Imagen: %1$lld × %2$lld", "Изображение: %1$lld × %2$lld", "Bild: %1$lld × %2$lld", "Image : %1$lld × %2$lld"),
    "mirroring.noAudio": ("Sound plays on the iPhone.", "El sonido se reproduce en el iPhone.", "Звук воспроизводится на iPhone.", "Der Ton läuft auf dem iPhone.", "Le son est joué sur l’iPhone."),
    "mirroring.stop": ("Stop Mirroring", "Detener duplicación", "Остановить трансляцию", "Spiegelung beenden", "Arrêter la recopie"),
    "mirroring.stop.hint": ("Stops screen capture and the connection to the TV", "Detiene la captura de pantalla y la conexión con la TV", "Останавливает захват экрана и соединение с ТВ", "Beendet Bildschirmaufnahme und Verbindung zum Fernseher", "Arrête la capture de l’écran et la connexion au téléviseur"),
    "mirroring.ended.title": ("Mirroring ended", "Duplicación finalizada", "Трансляция завершена", "Spiegelung beendet", "Recopie terminée"),
    "mirroring.ended.message": ("Screen capture and the TV connection are stopped.", "La captura de pantalla y la conexión con la TV se detuvieron.", "Захват экрана и соединение с телевизором остановлены.", "Bildschirmaufnahme und Verbindung zum Fernseher sind beendet.", "La capture de l’écran et la connexion au téléviseur sont arrêtées."),
    "mirroring.ended.test": ("The free mirroring test is over. To keep mirroring without an app time limit, continue with Remote Pro.", "La prueba gratuita de duplicación terminó. Para seguir sin límite de tiempo de la app, continúa con Remote Pro.", "Бесплатная проверка трансляции завершена. Чтобы транслировать без ограничения по времени, продолжите с Remote Pro.", "Der kostenlose Spiegelungstest ist vorbei. Für Spiegelung ohne App-Zeitlimit geht es mit Remote Pro weiter.", "Le test gratuit de recopie est terminé. Pour continuer sans limite de temps imposée par l’app, passez à Remote Pro."),
    "mirroring.backToSetup": ("Back to setup", "Volver a la configuración", "К настройке", "Zurück zur Einrichtung", "Retour à la configuration"),
    "diagnostic.mirroring.exhausted": ("The free mirroring test on this TV is used up.", "La prueba gratuita de duplicación en esta TV se agotó.", "Бесплатная проверка трансляции на этом ТВ использована.", "Der kostenlose Spiegelungstest auf diesem Fernseher ist aufgebraucht.", "Le test gratuit de recopie sur ce téléviseur est épuisé."),

}

PLURALS = {
    "diagnostic.mirroring.available": {
        "en": {"one": "Free test: mirroring for up to %lld second after the picture appears on the TV.", "other": "Free test: mirroring for up to %lld seconds after the picture appears on the TV."},
        "es": {"one": "Prueba gratuita: duplicación de hasta %lld segundo después de que aparezca la imagen en la TV.", "other": "Prueba gratuita: duplicación de hasta %lld segundos después de que aparezca la imagen en la TV."},
        "ru": {"one": "Бесплатная проверка: трансляция до %lld секунды после появления изображения на ТВ.", "few": "Бесплатная проверка: трансляция до %lld секунд после появления изображения на ТВ.",
               "many": "Бесплатная проверка: трансляция до %lld секунд после появления изображения на ТВ.", "other": "Бесплатная проверка: трансляция до %lld секунды после появления изображения на ТВ."},
        "de": {"one": "Kostenloser Test: Spiegelung bis zu %lld Sekunde, nachdem das Bild auf dem Fernseher erscheint.", "other": "Kostenloser Test: Spiegelung bis zu %lld Sekunden, nachdem das Bild auf dem Fernseher erscheint."},
        "fr": {"one": "Test gratuit : recopie jusqu’à %lld seconde après l’apparition de l’image sur le téléviseur.", "many": "Test gratuit : recopie jusqu’à %lld secondes après l’apparition de l’image sur le téléviseur.",
               "other": "Test gratuit : recopie jusqu’à %lld secondes après l’apparition de l’image sur le téléviseur."},
    },
    "diagnostic.mirroring.remaining": {
        "en": {"one": "Free test: %lld second left", "other": "Free test: %lld seconds left"},
        "es": {"one": "Prueba gratuita: queda %lld segundo", "other": "Prueba gratuita: quedan %lld segundos"},
        "ru": {"one": "Бесплатная проверка: осталась %lld секунда", "few": "Бесплатная проверка: осталось %lld секунды",
               "many": "Бесплатная проверка: осталось %lld секунд", "other": "Бесплатная проверка: осталось %lld секунды"},
        "de": {"one": "Kostenloser Test: noch %lld Sekunde", "other": "Kostenloser Test: noch %lld Sekunden"},
        "fr": {"one": "Test gratuit : %lld seconde restante", "many": "Test gratuit : %lld secondes restantes", "other": "Test gratuit : %lld secondes restantes"},
    },
}
